topgrade-rs/topgrade

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/build-and-test.yml
> Basic GitHub action

- src/steps/os/linux.rs
This PR should solve the issue reported by @Zahrun in [Issue #1032](https://github.com/r-darwish/topgrade/issues/1032#issue-1406047576)
> added deb-get update before deb-get upgrade

- src/config.rs
- src/main.rs
- src/steps/os/linux.rs
Solves request: https://github.com/r-darwish/topgrade/issues/1021#issue-1399502665
> Added Protonup support requested in issue#1021

- src/steps/os/linux.rs
> Adds openMandriva support

- src/steps/zsh.rs
> Fixes antigen update

- .gitignore
- build-all.sh
> Added build scripts for multiple platforms

- Cargo.lock
> Fix lock file

- .gitignore
- build-all.sh
> Adds simple Platform build script

- .github/workflows/release_win_osx.yml
> Add release targets

- Cargo.lock
- Cargo.toml
- build-all.sh
- src/main.rs
- src/steps/containers.rs
- src/steps/emacs.rs
- src/steps/generic.rs
- src/steps/git.rs
- src/steps/kakoune.rs
- src/steps/node.rs
- src/steps/os/linux.rs
- src/steps/os/unix.rs
- src/steps/powershell.rs
- src/steps/remote/ssh.rs
- src/steps/remote/vagrant.rs
- src/steps/tmux.rs
- src/steps/toolbx.rs
- src/steps/vim.rs
- src/steps/zsh.rs
- src/terminal.rs
This resolves all clippy errors
> Resolves clippy errors, please review!!!

- build-all.sh
> Build script improvements

- .github/workflows/release_win_osx.yml
- config.example.toml
- src/config.rs
- src/steps/os/archlinux.rs
> 35 add support for aura aur helper

- config.example.toml
- src/config.rs
- src/main.rs
- src/steps/os/linux.rs
> Extra options for distrobox

- src/main.rs
- src/steps/os/unix.rs
https://github.com/danhper/fundle
Tested on my machine :)
> Add `fundle` step

- .github/workflows/release-cross.yml
- .github/workflows/release.yml
- .github/workflows/update_aur.yml
> Release pipeline

- src/steps/os/android.rs
> Adds nala on android support

- README.md
- src/self_renamer.rs
- src/steps/tmux.rs
- src/steps/toolbx.rs
- topgrade.8
Closes #85.
Will create a pull request for the [documentation](https://github.com/topgrade-rs/topgrade-rs.github.io) soon.
> Use upper-case naming (Topgrade) everywhere

- src/steps/node.rs
> fix(steps/node): Only run global upgrade on Yarn 1.x

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/executor.rs
- src/main.rs
- src/steps/powershell.rs
- src/steps/remote/ssh.rs
- src/steps/tmux.rs
Fixes #107. @derphilipp would you be able to test this patch?
> Quote arguments when executing in a shell

- Cargo.lock
- Cargo.toml
- src/config.rs
> Changes version requirements to latest path of minor version

- src/steps/os/archlinux.rs
- src/steps/tmux.rs
> Resolves clippy errors

- src/steps/os/archlinux.rs
- src/steps/os/windows.rs
- src/steps/powershell.rs
- src/steps/tmux.rs
> Resolve clippy errors

- .github/workflows/check-and-lint.yaml
- .github/workflows/crates-publish.yml
> GitHub action cleanup2

- .github/workflows/check-and-lint.yaml
- src/steps/os/windows.rs
> Fix windows clippy errors

- CODE_OF_CONDUCT.md
> feat: add coc

- .github/workflows/crates-publish.yml
- .github/workflows/release-cross.yml
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- src/config.rs
- src/ctrlc/interrupted.rs
- src/executor.rs
- src/main.rs
- src/steps/generic.rs
- src/steps/node.rs
- src/steps/os/archlinux.rs
- src/steps/os/os_release/debian
- src/steps/os/windows.rs
- src/steps/powershell.rs
- src/steps/remote/ssh.rs
- src/steps/tmux.rs
Reverts topgrade-rs/topgrade#145
> Revert "Bug fixes"

- .github/workflows/check-and-lint.yaml
- .github/workflows/crates-publish.yml
- .github/workflows/release-cross.yml
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- src/config.rs
- src/ctrlc/interrupted.rs
- src/executor.rs
- src/main.rs
- src/steps/generic.rs
- src/steps/node.rs
- src/steps/os/archlinux.rs
- src/steps/os/os_release/debian
- src/steps/os/windows.rs
- src/steps/powershell.rs
- src/steps/remote/ssh.rs
- src/steps/tmux.rs
> Merge of bug-fixes with masters the second

- README.md
> Add info about Void Linux to README

- src/steps/node.rs
> Fix lack of separators for `pnpm`/`npm`/`yarn`

- Cargo.toml
> Added configuration for cargo-deb and cargo-generate-rpm

- src/execution_context.rs
- src/main.rs
- src/steps/remote/ssh.rs
- src/steps/tmux.rs
Fixes #117. Might fix #107 -- @derphilipp can you try this patch with the tmux-remote-ssh feature? (`run_in_tmux` + `remote_topgrades`)
> Fix tmux panic

- src/main.rs
- src/steps/os/freebsd.rs
Reverts topgrade-rs/topgrade#181
> Revert " Fix unattended package upgrades on FreeBSD"

- src/steps/node.rs
Closes #168 
Reopen of #196 with an external branch
Skipping review by @9999years because it got already reviewed in #196 and it passes all tests.
> Fixes NPM failure under sudo

- src/executor.rs
Fixes #200 
Considers 0 a success by default again
> Fix a bug with `status_checked_with_codes`

- src/steps/node.rs
> Npm rework

- Cargo.lock
- src/main.rs
- src/steps/os/freebsd.rs
Closes #179 
Created by @yonas 
> --yes flag support on freebsd

- src/execution_context.rs
- src/main.rs
- src/steps/generic.rs
- src/steps/node.rs
- src/steps/os/archlinux.rs
- src/steps/os/dragonfly.rs
- src/steps/os/freebsd.rs
- src/steps/os/linux.rs
- src/steps/os/windows.rs
- src/sudo.rs
This is a general refactor and improves on #219 for non-`sudo` sudos
> Add `Sudo` type

- src/main.rs
- src/steps/generic.rs
Closes #264 
- [] *Optional:* I have tested the code myself
@JustWhit3 please test
> Fixes vcpkg when installed as root

- src/steps/generic.rs
Closes #259 
@Zahrun please test
> Reopen of #267 Fixes rubygems on .deb distros

- config.example.toml
> Add dnf config to config example

- src/config.rs
- src/main.rs
- src/steps/os/linux.rs
> Add Devkitpro Pacman support

- src/steps/os/windows.rs
> Fix windows build

- src/steps/generic.rs
This is an attempt to fix #276, #289 and #299
@DottoDev Please take a look if this is fine with you. I moved the approach to a `match` block to keep the early return.
> Skip .NET when `dotnet tool list` is not successful

- src/steps/os/linux.rs
> Add openSUSE MicroOS support

- src/main.rs
- src/steps/generic.rs
> Fixes gem update --system requires sudo now

- config.example.toml
- src/config.rs
- src/main.rs
- src/steps/generic.rs
- src/steps/os/linux.rs
> Adds pip-review and pipupgrade support

- src/steps/upgrade.vim
> Add Lazy, a Neovim plugin manager

- config.example.toml
- src/config.rs
- src/main.rs
- src/steps/generic.rs
- src/steps/os/windows.rs
> WSL: Adds new wsl --update flags

- src/config.rs
- src/main.rs
- src/steps/generic.rs
- src/steps/os/linux.rs
> Adds AM Package Manager

- src/steps/upgrade.vim
> vim: Adds Astrovim support

- .github/workflows/check-and-lint.yaml
- Cross.toml
> CI: Update cross to v0.2.5

- src/steps/generic.rs
This PR adds a check to the pip3 step that skips if the file `EXTERNALLY-MANAGED` is present within python's `stdlib` folder, indicating that the base environment is managed by an external manager, such as the OS's package manager. Closes #365.
See: [PEP 668 – Marking Python base environments as “externally managed”](https://peps.python.org/pep-0668/)
> pip3: Check for EXTERNALLY-MANAGED (PEP 668)

- README.md
> Add Scoop manifest link for Windows installation

- config.example.toml
- src/config.rs
- src/main.rs
> Add no-self-update config and flag

- src/config.rs
- src/main.rs
- src/steps/generic.rs
> feat: support stew

- src/main.rs
- src/steps/os/unix.rs
> feat: support oh-my-bash

- src/config.rs
- src/main.rs
- src/steps/os/unix.rs
> feat: support maza

- src/steps/containers.rs
-----
Closes #406 
See [this comment](https://github.com/topgrade-rs/topgrade/issues/406#issuecomment-1558508725) for what the root cause is and how this patch works
```shell
$ docker image ls
REPOSITORY   TAG       IMAGE ID       CREATED       SIZE
alpine       latest    44dd6f223004   13 days ago   7.73MB
$ docker image inspect 44 --format '{{.Os}}/{{.Architecture}}'
linux/arm64
$ uname -m 
x86_64
$ ./target/debug/topgrade --only containers
── 12:45:56 - Containers ───────────────────────────────────────────────────────
latest: Pulling from library/alpine
Digest: sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11
Status: Image is up to date …
```
> fix: use --platform opt when pulling containers

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
> docs: CONTRIBUTING.md

- src/executor.rs
- src/main.rs
- src/steps/generic.rs
- src/steps/os/linux.rs
- src/steps/os/unix.rs
1. Clean up unnecessary qualifications, automated by IntelliJ Rust
> refactor: remove unnecessary qualification

- src/steps/os/linux.rs
Reverts topgrade-rs/topgrade#464
> Revert "fix: fix mist"

- .github/ISSUE_TEMPLATE/bug_report.md
-----
You can preview it here: https://github.com/SteveLauC/test_topgrade_pip/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=
1. Update the bug report issue template
1. Automatically add the `bug` label
2. Add the following sections
* Steps to reproduce
* Possible Cause (Optional)
* Problem persists without calling from topgrade
* Configuration file (Optional)
3. In the section `Verbose Output`, ask the user the full output of `topgrade -v` instead of just the output of the problematic command as this makes the debugging easier.
> chore: update bug report issue template

- src/config.rs
- src/main.rs
- src/steps/generic.rs
-----
[Bob](https://github.com/MordechaiHadad/bob) is a package manager for Neovim, to update installed stable and nightly versions of Neovim, [run the following command](https://github.com/MordechaiHadad/bob#-usage):
```shell
$ bob update --all
```
> feat: support Bob

- CONTRIBUTING.md
Looks like you use it, so should be included
> docs: add Karma commit messages to CONTRIBUTING.md

- src/steps/os/dragonfly.rs
> Ass assume-yes to DragonflyBSD

- src/steps/os/linux.rs
- src/steps/os/os_release/solus
-----
1. Add unit test for detecting Solus Linux
> test: unit test for Solus

- src/steps/os/windows.rs
> fix: WSL detection

- .github/ISSUE_TEMPLATE/bug_report.md
1. add SSH-related questions  to the issue template
> chore: add ssh-related questions in issue template

- src/config.rs
- src/main.rs
- src/steps/os/linux.rs
> feat: support LURE

- .github/workflows/check-and-lint.yaml
1. bump CI toolchain to the latest stable 1.72
> chore: bump ci toolchain

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> chore: update issue template label

- config.example.toml
- src/config.rs
- src/main.rs
- src/steps/git.rs
- src/steps/os/windows.rs
- src/steps/zsh.rs
some people seem very unhappy about this feature, I don't have time to develop it futher at the moment, and I'm getting a little sick of being painted as a bad guy just for contributing, so I'd like this functionality removed for now. The feature isn't worth the trouble to me.
> revert git pushing functionalities

- config.example.toml
- src/config.rs
- src/steps/zsh.rs
> refactor: cleanup for #615

- src/main.rs
- src/steps/os/unix.rs
If you developed a feature or a bug fix for someone else, and you do not have the
> Bun packages fixes

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/ctrlc/unix.rs
- src/utils.rs
-----
1. bump all the dependencies
2. Remove the libc dependency, and fully switch to Nix on UNIX OSes
> chore(deps): bump all deps

- CONTRIBUTING.md
> docs: fix a wrong preposition[skip ci]

- config.example.toml
- src/config.rs
- src/steps/os/unix.rs
> feat: add `fetch_head` configuration option into `brew`

- .github/dependabot.yml
> Keeping actions up to date with Dependabot

- README.md
- RELEASE_PROCEDURE.md
Since our release to Winget has been automated in #686, our documents should be updated accordingly.
> docs: update install doc with Winget

- config.example.toml
Document the homebrew configuration entries.
> docs: document brew config entries[skip ci]

- src/steps/os/openbsd.rs
- [Yes] The PR title is descriptive.
- [Yes] I have read `CONTRIBUTING.md`
- [Yes] The code compiles (`cargo build`)
- [Yes] The code passes rustfmt (`cargo fmt`)
- [Yes] The code passes clippy (`cargo clippy`)
- [Yes] The code passes tests (`cargo test`)
- [Yes] *Optional:* I have tested the code myself
> Fix OpenBSD Step failing to build with `E0599`

- Cargo.lock
- Cargo.toml
- src/config.rs
> chore: bump deps

- .github/workflows/build-and-test.yml
- Refine the testing matrix to include only stable and nightly versions of Rust
- Add 'fail_ci_if_error' option to Codecov step for stricter CI checks
- Ensure newline at end of file
> Update GitHub Actions workflow for Codecov integration

- src/steps/os/linux.rs
since it also uses apk the update/upgrade is identical to alpine/wolfi
> feat: add support for chimera linux

- src/steps/upgrade.vim
Runs `:MasonUpdate` as part of the vim updates.
> Run MasonUpdate as part of the vim updates

- .github/ISSUE_TEMPLATE/feature_request.md
Collection the following information in the feature request template so that we don't need to ask.
```
* Does it have a `--dry-run` option? i.e., print what should be done and exit
* Does it need the user to confirm the execution? And does it provide a `--yes`
option to skip this step?
```
> chore: collect `--dry-run` and `--yes` opts info in feature request template

- RELEASE_PROCEDURE.md
Update the release procedure, `mv` rather than `cp` should be used.
> docs: update release procedure

- README.md
GitHub reinstated my account, so let's keep going!
> docs: document that maintenance continues

- src/steps/os/linux.rs
- src/steps/os/os_release/funtoo
Adds support for updating [Funtoo Linux](https://www.funtoo.org) systems.
> feat(linux.rs): Add support for Funtoo

- src/steps/os/unix.rs
Nix version 2.21 changed how packages are upgraded. Fixes #782.
> Fix nix upgrades

- src/steps/os/windows.rs
Fix the Clippy warning on Windows.
> refactor: fix Windows clippy

- src/steps/generic.rs
Replicates https://github.com/topgrade-rs/topgrade/pull/350 for the [mise](https://mise.jdx.dev) package manager.
> Fix `RubyGems` issues for `mise` regarding `sudo`

- src/steps/tmux.rs
Based on [this comment](https://github.com/topgrade-rs/topgrade/issues/928#issuecomment-2396639729), fixes #928.
> fix: tmux unknown cmd: attach-client

- .github/workflows/release_to_aur.yml
Add updating the bin pkg on AUR, following discussion #879
> ci: add bin pkg to aur

- RELEASE_PROCEDURE.md
> docs: update release procedure that SECURITY.md should be updated in major release

- README.md
Add Fedora Copr to Readme.md, as of right now the it's support f40 and f41. I'm working on rawhide package one more.
> Add Fedora Copr to Readme.md

- src/steps/os/unix.rs
asdf, since version 0.15.0, won't support the `update` sub-command, so Topgrade should invoke this sub-command only if the version is lower than 0.15.0.
Closes #1007
> fix: do not run asdf update if version >= 0.15.0

- src/steps/os/openbsd.rs
> FIX: Allow for -beta OR -current detection and use the correct system upgrade command for the OpenBSD step

- locales/app.yml
> i18n(app.yml): new language lt

- CONTRIBUTING.md
* "You may want it to be sorted alphabetically" -> "Make sure it stays sorted alphabetically"
* Fix a few other minor issues in the doc
> Update CONTRIBUTING.md to reflect `enum Step` sort enforcement

- src/steps/generic.rs
This should fix #942, the impl is based on [this comment](https://github.com/topgrade-rs/topgrade/issues/942#issuecomment-2785749010).
Works for me with `uv 0.5.11 (c4d0caaee 2024-12-19)`
> fix: uv self update

- src/steps/generic.rs
Run `uv cache prune` in `uv` step when `cleanup` is enabled
> Run `uv cache prune` in `uv` step when `cleanup` is enabled

- src/steps/os/linux.rs
- src/steps/os/os_release/cachyos
Adds CachyOS as Arch derivative distro
Closes #1152
@jimmon89
Could you please build this branch (`cargo install topgrade --git https://github.com/GideonBear/topgrade --branch cachyos`) to test if it works?
> Add CachyOS support

- .github/workflows/create_release_assets.yml
Closes #1170
There are some more failing things but those have nothing to do with this. I think this should at least fix the binaries.
> Install rustfmt and clippy where necessary

- .github/workflows/release_to_homebrew.yml
> ci: fix homebrew ci, remove duplicate trigger event

- src/steps/os/unix.rs
This now includes a revision part which must be trimmed, e.g.
```
0.18.0 (revision unknown)
```
> Handle another format change in asdf version

- src/steps/generic.rs
Closes #1199
@mortenlj can you verify that this solves your problem?
Install: `cargo install --git https://github.com/GideonBear/topgrade --branch uv-fix`
Run: `~/.cargo/bin/topgrade`
> Catch secondary uv self-update error

- README.md
> docs: add Discord invite link to README

- src/runner.rs
- src/steps/generic.rs
- src/utils.rs
Applies fixes identified by the version of clippy in rust 1.91-nightly
- [ x ] The PR title is descriptive
- [ x ] I have read `CONTRIBUTING.md`
- [ x ] *Optional:* I have tested the code myself
- [ n/a ] If this PR introduces new user-facing messages they are translated
> Clippy fixes from rust 1.91 nightly

- src/steps/os/unix.rs
Fixes nix upgrade command selection for nix profiles in `$XDG_STATE_HOME` instead of `~/.nix_profile`
- [N/A] If this PR introduces new user-facing messages they are translated
> fix nix upgrade command selection for profiles in XDG_STATE_HOME
