src/config.rs

Default value for using ostree on dnf systems was true, which produced errors when run on non ostree systems. Because most users run non-ostree system this setting got changed to false.

Change dnf ostree default value

---

src/steps/os/linux.rs

Fixes deb-get upgrade process

---

src/steps/os/unix.rs

It's just `fisher` (no `update`)
```
fisher: unknown flag or command "update"
usage: fisher add <package...>     Add packages
fisher rm  <package...>     Remove packages
fisher                      Update all packages
fisher ls  [<regex>]        List installed packages matching <regex>
fisher --help               Show this help
fisher --version            Show the current version
fisher self-update          Update to the latest version
fisher self-uninstall       Uninstall from your system
```

Fix broken fisher update command

---

Cargo.toml
build-all.sh

Changed binary name to be backwards compatible, version bump to 10.0.0

---

src/steps/os/unix.rs
src/steps/zsh.rs

Fix nix profile upgrade command & add profile path detection

---

src/steps/os/unix.rs

Follow-up of https://github.com/topgrade-rs/topgrade/pull/37#issuecomment-1283844506
Tested for both v3 and v4 :)

Backwards compatibility with fisher v3

---

.github/workflows/crates-publish.yml

In `Cargo.toml` the version is 10.0.0 but the version on `crates.io` is only 9. There is no reason
to manage publishes ourselves. No more need to think when a publish is necessary.

Add(CI): For automatically publishing on new versions

---

src/steps/git.rs

Current code panics when update of git repositories is run on repository with no remotes. This is a regression I noticed after recent update form crates.io.
Looking around I found that the issue was introduced in #60, simply reverting the offending line fixed the issue for me. I don't get any clippy warnings for this line after changing it back (maybe there was a false positive?).

Don't panic on git repository with no remote

---

src/steps/upgrade.vim
src/steps/vim.rs

Fix neovim upgrade (command line arguments are different from the vim's one) and fix the upgrade script when using Packer.
https://asciinema.org/a/vxfsGPHxp0BteRssN4OrpuvvR

Fix neovim upgrade

---

src/config.rs
src/main.rs
src/steps/os/linux.rs

feat: added distrobox

---

Cargo.lock
Cargo.toml
src/config.rs

Clap 4 no longer depends on `textwrap` or `indexmap` - slightly better build time/size. Additionally, we had textwrap in a yanked version in Cargo.lock.
Notably, clap no longer colors help printouts in this version, only basic text decorations like underscores.
I also added some `value_name` fields to better describe the flags that have values. I also added `num_args` to the `--custom-commands` so we can accept multiple custom command names.

Bump clap version to 4.0

---

src/config.rs
src/main.rs
src/steps/generic.rs

This upgrades `ghcup`: https://www.haskell.org/ghcup/
Potential work: if `stack` is installed through `ghcup`, you're not supposed to run `stack upgrade`, so I could potentially patch this to ignore the `stack` step when `ghcup` is present. (And/or detect if `stack` is a `ghcup`-installed `stack`.)
- Yes but it ran zero tests? Also I didn't write any

Add `ghcup` step

---

src/config.rs
src/main.rs
src/steps/os/unix.rs

https://github.com/thoughtbot/rcm
Tested on my machine with `cargo run -- --only rcm`.
Should I add an `#[serde(alias = "rcup")]` on the `Step` item? (The tool suite is called `rcm`, and `rcup` is the one that actually updates the dotfiles.)

Add `rcm` step

---

src/main.rs
src/steps/os/mod.rs
src/steps/os/openbsd.rs

This PR adds support for OpenBSD (ports & system upgrade).
Signed-off-by: Benjamin Stuerz <benni@stuerz.xyz>

OpenBSD support

---

.vscode/launch.json
src/self_update.rs

Fixes some references to the original topgrade repo

---

src/self_update.rs

The commit 9105a8aac is not formatted, which breaks the CI check.

style(self_update): Run cargo fmt

---

.github/workflows/release-cross.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml
README.md
src/config.rs
src/self_update.rs

This PR reverts the clap version bump introduced in #81 because clap in v4.x keeps failing the CD pipeline.

Revert clap version bump

---

src/steps/emacs.rs
src/steps/generic.rs
src/steps/kakoune.rs
src/steps/os/macos.rs
src/steps/os/unix.rs
src/steps/remote/ssh.rs
src/steps/tmux.rs
src/steps/vim.rs
src/terminal.rs

clippy version: clippy 0.1.66 (11ebe651 2022-11-01)

refactor: Run cargo clippy --fix

---

src/main.rs
src/steps/node.rs

We reuse the `NPM` structure, and use NPMVariant to distinguish “npm” and “pnpm”. Besides, we also decouple the name display from `NPM` structure.
This refactor also simplifies the development of a upgrader for a NPM fork.
BREAKING CHANGES: `pnpm` is now a separated step.
This fixes https://github.com/topgrade-rs/topgrade/issues/68.

refactor!(steps/node): make PNPM a separated step

---

.github/workflows/check-and-lint.yaml
src/steps/os/windows.rs

Get windows to finish clippy without errors

---

.github/workflows/check-and-lint.yaml
src/steps/generic.rs

Closes #138 
Since snapd handles updates for us, and it doesn't work anyways, skip if the install uses snap.

Fix for gcloud snap issue

---

src/steps/os/linux.rs

* Check if distrobox exists before running step

bugfix Closing #150 (#151)

---

src/config.rs

Improve help prompt value names

---

src/runner.rs
src/terminal.rs

Here's what the error encountered in #167 looks like with this change:
```
pnpm failed: Command failed: `/usr/local/bin/pnpm root -g`
Stdout:
ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
Caused by:
`/usr/local/bin/pnpm` failed: exit status: 1
Retry? (y)es/(N)o/(s)hell/(q)uit
```
Note that:
- It tells you what step failed (`pnpm`)
- It tells you what command was run and which arguments were passed to it
- It shows you the output (stdout and stderr) of the program called (unless the output was already displayed to the user)
- It shows the exit status of the command

Print errors when steps fail

---

src/steps/os/android.rs

Fix compilation on Android

---

src/steps/os/freebsd.rs

I also fixed a couple of clippy warnings, but not all, as those also target other platforms, so it makes sense to address them in a new PR.

Fix compilation on FreeBSD

---

src/steps/os/android.rs
src/steps/os/unix.rs

- Restrict Homebrew-related code to Linux and macOS 
- Don't import `require_option` on OSes with no GNOME support 
- Clippy fixes for Android

Further clippy fixes

---

.github/workflows/check-and-lint.yaml
Cross.toml
README.md

This PR is pretty much ready (reviews aside), but it currently depends on the following PRs to be merged first (in order for the CI to run successfully):
---
Changes:
- Bump minimum Rust version to 1.60 (required by the `time` crate).
- Bump [actions/checkout](https://github.com/actions/checkout) to `v3`, fixing a bunch of warnings.
- Replace unmaintained [actions-rs/cargo](https://github.com/actions-rs/cargo) by [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain).
- Run Rustfmt only once.
- Add support for cached dependencies (via [Swatinem/rust-cache](https://github.com/Swatinem/rust-cache)).
- Add Android target (cross-compiled using [cross](https://github.com/cross-rs/cross)).
- Add FreeBSD target (cross-compiled using [cross](https://github.com/cross-rs/cross)).

CI improvements + Android and FreeBSD targets

---

src/main.rs
src/steps/os/unix.rs

Fixes https://github.com/topgrade-rs/topgrade/issues/9
It definitely works, although if you just install `fisher` (e.g. with `brew install fisher`) and don't do anything else, it's not too happy:
```
―― 22:07:34 - Fisher ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
fisher: "/Users/wiggles/.config/fish/fish_plugins" file not found: "update"
Retry? (y)es/(N)o/(s)hell/(q)uit
```
I think `~/.config/fish/fish_plugins` is where `fisher` expects to find a list of plugins. I don't use `fisher` currently, though.

Run `fisher` if `fish -c 'type -t fisher'` is OK

---

src/main.rs
src/steps/os/freebsd.rs

```
$ cargo clippy
warning: constant `INTEL_BREW` is never used
--> src/steps/os/unix.rs:20:1
|
20 | const INTEL_BREW: &str = "/usr/local/bin/brew";
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: constant `ARM_BREW` is never used
--> src/steps/os/unix.rs:21:1
|
21 | const ARM_BREW: &str = "/opt/homebrew/bin/brew";
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warning: associated function `binary_name` is never used
--> src/steps/os/unix.rs:32:8
|
32 |     fn binary_name(self) -> &'static str {
|        ^^^^^^^^^^^
warning: associated function `both_both_exist` is never used
--> src/steps/os/unix.rs:45:8
|
45 |     fn both_both_exist() -> bool {
|        ^^^^^^^^^^^^^^^
warning: associated function `step_title` is never used
--> …
```

 Fix unattended package upgrades on FreeBSD

---

src/steps/os/freebsd.rs
src/steps/upgrade.vim

This adds `:TSUpdate` (haha `TS`) to the Vim upgrade script. Fixes #183.
In the future, I'd like the Vim upgrade to display its output. Right now if I show the output, it's kinda messy due to weirdness with some of the plugins I use:
```
―― 14:27:05 - Neovim ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Error detected while processing BufWinEnter Autocommands for "*":
E495: no autocommand file name to substitute for "<afile>"
Error detected while processing BufEnter Autocommands for "*"..function <SNR>42_detect_indent:
line   10:
E495: no autocommand file name to substitute for "<afile>"
TreeSitter Update
All parsers are up-to-date!
PackerPlugins upgraded
```
This is due to the way we run Vim (headless).

Add Treesitter support to Vim upgrade

---

Cargo.lock
Cargo.toml
src/command.rs
src/config.rs
src/ctrlc/windows.rs
src/executor.rs
src/main.rs
src/runner.rs
src/self_renamer.rs
src/steps/containers.rs
src/steps/generic.rs
src/steps/git.rs
src/steps/node.rs
src/steps/os/linux.rs
src/steps/os/macos.rs
src/steps/os/unix.rs
src/steps/os/windows.rs
src/steps/remote/vagrant.rs
src/steps/toolbx.rs
src/steps/vim.rs
src/steps/zsh.rs
src/terminal.rs
src/utils.rs

`tracing` is the standard logging library, used by rustc. Let's use it. In a future PR we can start leaning on `tracing`'s tools, annotating functions, and so on.
Might tweak the output format a bit more.

Use `tracing`

---

.github/workflows/check-and-lint.yaml
Cargo.lock
Cargo.toml
src/config.rs
src/steps/os/freebsd.rs
src/utils.rs

This also removes the `sys-info` crate, because it offers much more features than we currently use.
Additionally, `sys-info` was preventing me to cross-compile for NetBSD.
Since we were just using the `hostname()` function from the crate, I went ahead and stole it.

CI: Add NetBSD target 

---

src/steps/os/dragonfly.rs

CI for DragonFly BSD will have to wait for the next stable release of cross due to [this bug](https://github.com/cross-rs/cross/issues/1141), but I tested the changes locally and they worked.

Fix compilation on DragonFly BSD

---

.github/workflows/check-and-lint.yaml

This PR prevents `clippy` from being installed in the Rustfmt job (and vice-versa). It also prevents the (unnecessary) installation of the target toolchain on the host.

CI: Install only necessary components

---

config.example.toml
src/config.rs
src/main.rs
src/steps/node.rs
src/sudo.rs
src/utils.rs

Closes #205 by adding a `pre_sudo` option (defaults to `false`) which calls `sudo -v` after any `pre_commands` in order to update the current session's cached credentials.

Add `pre_sudo` option

---

src/steps/os/dragonfly.rs

Fix clippy warning for DragonFly BSD

---

src/config.rs
src/steps/generic.rs
src/steps/os/archlinux.rs

if garuda-update is in our path use that instead of directly calling pacman/paru/powerpill. There's more stuff the update script does that you're just asking for problems if you upgrade partially.
I created a feature request here:
https://github.com/topgrade-rs/topgrade/issues/226

Add garuda-update

---

src/steps/generic.rs

This is a follow-up to a review comment added in https://github.com/topgrade-rs/topgrade/pull/248#discussion_r1039102177
cc @mouse07410 @DottoDev

Fix misleading log message when detecting rbenv

---

src/steps/os/unix.rs

Closes #261 
@bagel897 please test

adds fish_update_completions to fish step

---

src/terminal.rs

Don't show desktop notification on error (if `skip_notify = true`)

---

config.example.toml
src/config.rs
src/steps/os/archlinux.rs

By default, `garuda-update` only updates system packages, which in my opinion is not a good default behavior for us.
Additionally, it also updates the repositories' mirror list every time, slowing things down considerably, so I decided to disable this behavior. 
According to their [wiki page](https://wiki.garudalinux.org/en/garuda-update), and based on a cursory reading I did of their [update script](https://gitlab.com/garuda-linux/packages/stable-pkgbuilds/garuda-update/-/blob/59fd4b1e4f4887d23fcb1ac9603b497e4b2f89d7/main-update), this behavior can be changed in the following order of preference:
1. Environment variables.
2. `/etc/garuda/garuda-update/config`.
3. Command-line arguments passed to `garuda-update` directly.
I decided to go with the first option, so that topgrade users can …

Make garuda-update update AUR packages by default

---

src/steps/os/linux.rs

feat(pacstall): add `-y` flag variant

---

src/terminal.rs

Fix small typo in warning when `notify-send` fails

---

src/main.rs

Adds notify-send timeout of 10s

---

src/steps/os/unix.rs

- [*] The PR title is descriptive.
- [*] The code compiles (`cargo build`)
- [*] The code passes rustfmt (`cargo fmt`)
- [*] The code passes clippy (`cargo clippy`)
- [*] The code passes tests (`cargo test`)
- [*] *Optional:* I have tested the code myself
- [*] I also tested that Topgrade skips the step where needed

Fix missing separator for Pkgin (pkgsrc)

---

src/steps/upgrade.vim

fix upgrade order of (n)vim plugins

---

src/config.rs
src/steps/os/linux.rs

Don't run yum when rpm-ostree is available

---

src/steps/os/linux.rs

Use fixed nala path instead of which(nala)

---

config.example.toml
src/config.rs
src/main.rs

Adds notify-send bug warning when topgrade is run

---

config.example.toml
src/config.rs
src/steps/os/linux.rs

nix: Adds additional arguments support

---

src/main.rs

Bug was introduced in f1e4009. Fixes #337.

fix ignored config `display_preamble = false`

---

src/steps/generic.rs

Tested on macOS 13.2 (M1 Pro) with homebrew zsh.

run_custom_command: use interactive shell on unix

---

src/steps/generic.rs

ruby_gems: Fixes asdf

---

src/main.rs

- [ x] The PR title is descriptive.
- [ x] The code compiles (`cargo build`)
- [ x] The code passes rustfmt (`cargo fmt`)
- [ x] The code passes clippy (`cargo clippy`)
- [ x] The code passes tests (`cargo test`)
- [ x] *Optional:* I have tested the code myself
- [x ] I also tested that Topgrade skips the step where needed
On macos I got the warning about `notify-send` and had no idea macos even used it.
Turns out, it doesn't. My arch boxes do tho. So I tweaked things such that the warning only appears on linux hosts vs say unix or macos hosts.
Tested it on my macs and didn't get the warning. Tested it on arch and was dutifully warned.
There's probably a slicker way to do do it than a #cfg block, but hey, this works. I'm pretty sure this will do the right thing on windows boxes too but …

Silence misleading warning on other platforms.

---

src/steps/os/linux.rs

apt: Recognise mist

---

src/steps/os/linux.rs

`pacdef` will release a new major version in the near future. Part of the release is a breaking change for the command line arguments.
This commit checks which version of pacdef is installed by parsing `pacdef version`, and uses either the old or the new syntax.

pacdef: support new version 1.x

---

src/steps/generic.rs

This PR adds a cleanup step for cargo using the cargo-cache crate if cleanup is enabled in the configs. It will also warn the user if cargo-clean is not found, similar to cargo-install-update.

cargo: add cleanup step (using cargo-cache)

---

src/main.rs

skip skip-notify warning on Win

---

src/main.rs
src/steps/generic.rs

Running `rustup update` causes it to update itself when appropriate.

No need to run self-update in Rustup

---

src/config.rs
src/steps/os/linux.rs

Closes #387 
@AWHubGit could you check this patch out

Assume Fedora Silverblue based on os-release and not on existence of rpm-ostree

---

Cargo.lock
Cargo.toml
src/config.rs
src/execution_context.rs
src/main.rs
src/steps/emacs.rs
src/steps/generic.rs
src/steps/node.rs
src/steps/os/unix.rs
src/steps/os/windows.rs
src/steps/tmux.rs
src/steps/vim.rs
src/steps/zsh.rs

In most places, the `BaseDirs` struct is just used for getting the user's home directory.
I've made it a global lazy variable & replaced all instances of `base_dirs.home_dir()` with `HOME_DIR` (commit 1).
After that, I removed all the places where `base_dirs` or `ctx` was no longer required (commit 2).
Finally, I replaced the `directories` crate with the `etcetera` crate (commit 3), since none of the crates use the `~/Library` paths returned for macOS. Also created a global variable for `XDG_DIRS` & `WINDOWS_DIRS` (if compiling for Windows) to remove unnecessary argument passing.
I only have a few applications installed, but it is working for me on macOS. In case you want to be extra cautious, you could release commit 1/2 & commit 3 separately.

Replace `directories` with `home` & `etcetera`

---

src/config.rs

Add the ability to have the config file in $XDG_CONFIG_HOME/topgrade/topgrade.toml

---

config.example.toml
src/config.rs
src/steps/os/linux.rs

Make `zypper dist-upgrade` opt-in on SLE/Leap

---

src/steps/node.rs

Differentiate NPM and PNPM steps in name

---

config.example.toml
src/config.rs
src/main.rs
src/steps/generic.rs

I've always used the command `pip-review --local --auto` to upgrade python packages since I install them in my home directory. Since topgrade skips the `--local` flag by default, I added it myself. I made it a new step because some people may have both local and system-wide packages installed on their system.

Adding local pip-review

---

src/steps/os/linux.rs

-----
Related to #429, see [this comment](https://github.com/topgrade-rs/topgrade/issues/429?notification_referrer_id=NT_kwDOBcZH5LM2NDY2OTkzNjAxOjk2ODgwNjEy#issuecomment-1548867273)

fix: run deb-get without sudo

---

src/steps/zsh.rs

Closes #426
cc @lime-desu who has already found this and posted [it](https://github.com/topgrade-rs/topgrade/discussions/361) in discussions

fix: use env ZSH to compose oh-my-zsh install dir

---

src/main.rs
src/steps/generic.rs
src/steps/git.rs
src/steps/go.rs
src/steps/os/dragonfly.rs
src/steps/os/freebsd.rs
src/steps/os/linux.rs
src/steps/os/macos.rs
src/steps/os/openbsd.rs
src/steps/os/unix.rs
src/steps/os/windows.rs
src/steps/tmux.rs
src/steps/vim.rs
src/steps/zsh.rs

Closes #223 
The step functions take all sorts of parameters, when I first contributed to `topgrade`, this really confused me and is obviously unfriendly to the new contributors, we should make them all consistent, and add some doc on how to add new steps in `CONTRIBUTING.md`

refactor: make all step functions take &ExectutionContext

---

Cargo.lock
Cargo.toml
config.example.toml
src/config.rs
src/main.rs
src/terminal.rs

Linux now use the crate [notify-rust](https://crates.io/crates/notify-rust). BSD could use that crate too.
For Windows we could use [winrt-notification](https://crates.io/crates/winrt-notification).

Merge code for desktop notification between MacOS and Linux

---

src/steps/os/linux.rs

Allow apt-get update to continue to apt-get upgrade with error code 100

---

src/main.rs
src/steps/os/linux.rs

1. Rename two update functions to `run_xxx()`
2. Some cleanup in `main.rs`, put all update functions that belong to a specific OS together

refactor: rename update fn name & some cleanup

---

src/steps/os/linux.rs
src/steps/os/os_release/deepin

Support [deepin](https://www.deepin.org/index/en) Linux, it is a distro based on `debian`. In its `/etc/os-release` file, there is no `ID_LIKE` field so `topgrade` can not fall back to `debian` in the current impl.
```shell
$ topgrade --dry-run --only system
Error detecting current distribution: Unknown Linux Distribution
$ topgrade --dry-run --only system
── 13:21:35 - System update ────────────────────────────────────────────────────
Dry running: /usr/bin/sudo apt-get update
Dry running: /usr/bin/sudo apt-get dist-upgrade
── 13:21:35 - Summary ──────────────────────────────────────────────────────────
System update: OK
```

feat: support deepin OS

---

src/steps/containers.rs

-----
This issue is due to a mistake made in #435, in that PR, while listing installed containers, I use `'/'` to separate `repo_tag` and `id`, in the case where `repo_tag` contains `'/'`, e.g., `nixos/nix`, this approach won't work and will panic the whole program:
```shell
$ topgrade --only containers
── 14:28:54 - Containers ───────────────────────────────────────────────────────
The application panicked (crashed).
Message:  assertion failed: `(left == right)`
left: `3`,
right: `2`
Location: src/steps/containers.rs:83
```
Related code is here:
```rust
let split_res = line.split('/').collect::<Vec<&str>>();
assert_eq!(split_res.len(), 2);
```
If `repo_tag` …

fix: fix panic during container update

---

src/steps/os/linux.rs
src/steps/os/os_release/vanilla

----
Ref:
* [manual](https://github.com/Vanilla-OS/apx/blob/fd7a42edbe5d3f9d251267f51211648394eddf45/man/man1/apx.1#L697-L713) for `apx update`
* [manual](https://github.com/Vanilla-OS/apx/blob/fd7a42edbe5d3f9d251267f51211648394eddf45/man/man1/apx.1#L660-L670) for `apx upgrade`
They do have a [rendered online manual page](https://documentation.vanillaos.org/docs/apx/manpage), but it is kinda outdated.

feat: support Vanilla Linux

---

config.example.toml
src/config.rs
src/steps/generic.rs

feat: Add arguments to pipupgrade and fix enable_pipupgrade check

---

src/config.rs

- [x The PR title is descriptive.

fix: Write to correct config path when none exists.

---

src/steps/os/linux.rs

-----
1. `AM` should not be executed with sudo
2. `am -u` requires the user to answer a prompt, `am -U` does not. So when [`assume_yes = true`](https://github.com/topgrade-rs/topgrade/blob/234ad4bdd7695e5c9961c0930bf9746dcb4a5635/config.example.toml#L9) is set in the configuration, we use `am -U`, otherwise, use `am -u`.
Closes #453

fix: run AM without sudo

---

config.example.toml
src/config.rs

Default config will now work (with commented out include section).

fix: Handle '# [include]'. Update default config

---

src/steps/git.rs

-----
We should warn the user about the bad pattern before skipping the step git:
```shell
$ cat ~/.config/topgrade/topgrade.toml
[git]
pull_predefined = false
repos = [
"bad_pattern"
]
$ topgrade --dry-run --only git_repos
$ echo $?
0
$ ./target/debug/topgrade --dry-run --only git_repos
Path bad_pattern did not contain any git repositories
```
-----
I think besides `Skipped`, we should define another state `NotFound`, when a step's binary is not found in `$PATH`, we use `NotFound` to skip this step instead of `Skipped`. For the case where the binary is found but some conditions are not satisfied during execution (e.g., for git step, no repo is found, like the …

fix: warn user about bad pattern paths before skipping step git

---

CONTRIBUTING.md
config.example.toml

-----
1. Update the example cases given in `CONTRIBUTING.md` where arguments in addition to `ctx` are required
> The old example is not suitable as `cleanup` is included in `ExecutionContext`, we don't need that `cleanup` argument, the related code will be fixed in #457
2. Fix some typos in `CONTRIBUTING.md`
3. Uncomment `[include]` section in `config.example.toml`

docs: update CONTRIBUTING.md & config.example.toml

---

src/main.rs
src/steps/os/dragonfly.rs
src/steps/os/freebsd.rs
src/steps/os/unix.rs
src/steps/os/windows.rs

-----
1. Update 4 update functions' argument to `&ExectutionContext`
2. In `main.rs`, function `run()`, put all update functions together like this:
```rust
#[cfg(windows)]
{ }
#[cfg(target_os = "linux")]
{ }
#[cfg(target_os = "macos")]
{ }
#[cfg(target_os = "dragonfly")]
{ }
#[cfg(target_os = "freebsd")]
{ }
#[cfg(target_os = "openbsd")]
{ }
#[cfg(target_os = "android")]
{ }
#[cfg(unix)]
{ }
#[cfg(not(any(
target_os = "freebsd",
target_os = "openbsd",
target_os = "netbsd",
target_os = "dragonfly"
)))]
{ }
```
so that contributors can easily find what is the appropriate place for their new update functions.
One thing to note is that the order of these update …

refactor: make update fn take &ExectionContext & put update fn together

---

src/steps/os/linux.rs

Closes #463, cc @jonathan-realman
With this patch, `mist` should be invoked like:
```shell
$ sudo mist update
$ sudo mist upgrade
```

fix: fix mist

---

src/config.rs

When config file(s) exist in `topgrade.d` but no `topgrade.toml` exists, `ensure()`  does not create a default config file.  This causes an error as `read()` assumes the `topgrade.toml` file exists.
This PR assumes the desired behavior is to use just the contents of the files in `topgrade.d`.
Else, one could change `ensure()` to create `topgrade.toml`.

fix: handle no topgrade.toml but files in topgrade.d

---

src/steps/upgrade.vim

AstroNvim switched to using `Lazy` to manage plugins some weeks back.
For users of AstroNvim:
- Without this PR, topgrade runs `Lazy sync` (since `:Lazy` exists via AstroNvim) and quits without updating AstroNvim.
- With this PR, AstroUpdate is called if it exists before checking for existence of `Lazy.nvim`. AstroUpdate will update the plugins (using Lazy currently) as needed. So the explicit call to `Lazy sync` in `upgrade.vim` becomes unnecessary.
I suggest that users of AstroNvim add
```
updater = {
skip_prompts = true,
},
```
to their `init.lua` to automatically confirm and quit AstroNvim after `AstroUpdate` and skip the redundant call to `Lazy sync`.
Users not using AstroNvim should be unaffected.
means …

fix: Run AstroUpdate before Lazy sync

---

src/steps/generic.rs
src/utils.rs

-----
Closes #470, cc @soredake
On Windows, when you install `python` through `winget`, an actual `python` binary will be installed as well as a `python3` shim, the shim is executable **but will launch the Microsoft App store instead of a Python shell**. Before this PR, `topgrade` called `python3` under the hood, which is a shim under this case.
We check both `python` and `python3` through `.and_then(check_is_python_2_or_shim)`, if `python` is available and is a valid Python 3, we prefer to use it. This is fine as on most systems, `python` is a link to the default `python3`.

fix(pip3): prefer python when available

---

.github/workflows/test.yaml
src/config.rs

-----
Closes #451
1. Add test for:
1. check the default configuration in `config.example.toml` is valid in `config.rs` (unit test)
2. `topgrade`  will create a default configuration file in `~/.config.topgrade.toml` (CI)
1. It seems that `.github/workflow/test.yaml` is not being run in the CI, only `check-and-lint.yaml` is.
2. Unit tests are not covered in the CI for the reason stated in `1`

test: test for config file creation and default config file parsing

---

src/config.rs

-----
In the previous implementation, config entry `sudo_command` is not under the section `[misc]`, but in our example config file, it is. This PR moves it to the section `[misc]`, closes #483.
```
$ cat ~/.config/topgrade.toml
[misc]
sudo_command = "please"
$ topgrade 
ERROR Failed to deserialize /home/steve/.config/topgrade/topgrade.toml: unknown field `sudo_command`, expected one of `pre_sudo`, `git_repos`, `predefined_git_repos`, `disable`, `ignore_failures`, `remote_topgrades`, `remote_topgrade_path`, `ssh_arguments`, `git_arguments`, `tmux_arguments`, `set_title`, `display_time`, `assume_yes`, `yay_arguments`, `aura_aur_arguments`, `aura_pacman_arguments`, …
```

refactor(config): move sudo_command to section misc

---

src/steps/generic.rs

Please update just the base env, it is common to have others environment activated and I don't want to update them. The important bit that should be updated is the base env, I modified the code to update just the base environment in conda and also in mamba.

Update only base conda env

---

.github/workflows/code-coverage.yml
.github/workflows/test-config-creation.yml

-----
CI `code-coverage` is kinda useless? It makes CI fail for almost all the PRs, this PR separates `code-coverage` and `test-config-creation` so that we can disable `code-coverage`.

ci: separate code-coverage and test-config-creation

---

src/steps/os/unix.rs

Closes #476 
cc @BackSpace54, [here](https://github.com/SteveLauC/topgrade/releases/tag/oh-my-bash-fix) is a build for Linux with this patch included, you can try it so that we can know if this patch works or not:)

fix: fix wrong path in oh-my-bash

---

config.example.toml

-----
1. Document 4 missing sections in `config.example.toml`
1. post_command
2. yarn
3. vim
4. vagrant
2. Reorder the sections in `config.example.toml` so that they correspond to the order used by `struct ConfigFile`

docs(config): document 4 missing sections in example config file

---

src/steps/generic.rs

[NixOS](https://github.com/NixOS/nixpkgs) packages spicetify as `spicetify-cli` which means the step is skipped on NixOS machines even if spicetify is actually present.

fix(generic): add alternate binary name for spicetify

---

src/steps/toolbx.rs

This PR refines the `toolbx` update step, which is currently implemented as entering into the target toolbx container and then executing the running `topgrade` executable from there. The following changes to topgrades behavior in the toolbx container are made:
- Don't perform anther topgrade self-update (because the "outer" topgrade will have done that before)
- Don't show "update finished" notifications (because this is confusing and leads users to believe that topgrade finished rather quickly)

steps/toolbx: Don't self-update and don't send notifications

---

src/steps/emacs.rs

A new [`non_minimal_cfg`](https://rust-lang.github.io/rust-clippy/master/index.html#/non_minimal_cfg) warning was added in Rust 1.71.0, fixing the occurence here

Fix clippy warning about non_minimal_cfg

---

src/steps/os/linux.rs

Add `assume-yes` to :
- SUSE (Micro) - TW (`zypper`)
- PCLinux OS (`apt`)
- Solus (`eopkg`)
- `pacdef`
- Clear Linux (`swupd`)

Add assume-yes to more Linux managers

---

.github/workflows/crates-publish.yml
.github/workflows/update_pypi.yml
README.md
pyproject.toml

-----
1. Add some necessary file to enable automatic PyPI release
2. Disale crates.io release after editing a release
Closes #462 
Topgrade on PyPI is still under my personal account as they haven't approved my request to create the organization...

CI: release to PyPI

---

src/execution_context.rs
src/steps/zsh.rs

Closes #477 
-----
See [this comment](https://github.com/topgrade-rs/topgrade/issues/477#issuecomment-1629936602)
We judge if we are running under `ssh` [through environment variables `SSH_CLIENT` and `SSH_TTY`](https://unix.stackexchange.com/a/9607/498440), if yes, we spawn a `zsh` process and make `zshrc` sourced, then we extract the environment variable `ZSH` from this process, and set it in the `topgrade` process.
1. #477 
2. If a user has a custom `oh-my-zsh` installation (not `~/.oh-my-zsh`) on a remote machine and the user tries to update `oh-my-zsh` on that remote machine through topgrade, then this step will be skipped as environment variable `ZSH` is …

fix(oh-my-zsh): fix remote oh-my-zsh issue

---

.github/workflows/check-and-lint.yaml
README.md
src/steps/os/unix.rs

-----
1. bump CI toolchain to the latest stable toolchain: 1.71.0
2. Correct the MSRV in README

chore: bump ci toolchain and MSRV

---

config.example.toml
src/config.rs
src/steps/os/unix.rs

-----
1. Add a config entry, enabling users to add extra arguments to Home Manager, closes #497

feat: extra arguments for Home Manager

---

src/steps/os/dragonfly.rs
src/steps/os/linux.rs

-----
1. Change the yes option from
```rust
.arg(if ctx.config().yes(Step::System) { "-y" } else { "" })
```
to
```rust
if ctx.config().yes(Step::System) {
cmd.arg("-y");
}
```

fix: fix Linux and DragonFlyBSD yes option

---

src/main.rs

Steps that don't require `sudo` like `flatpak` and `brew` are executed before steps that require `sudo` like `snap` and `pacstall`. This times out the sudo privilege and topgrade waits for the password. Ideally, sending a notification, when sudo is required, is a better solution but reordering the steps would work for most cases.

Prioritize sudo steps to prevent sudo timeout

---

src/config.rs
src/main.rs
src/steps/generic.rs

MiKTeX is a modern TeX distribution, with integrated package manager which installs missing components from the Internet, if required. This allows you to keep your TeX installation as minimal as possible
Links of the project:
- https://miktex.org/
- https://github.com/MiKTeX/miktex
I use Topgrade regularly with great success but observed this upgrade is still missing. I consequently made this PR to fix it.
Update is done with the integrated updater with the command `miktex packages update`, and I tested myself on Ubuntu 20.04.

feat: support miktex packages update

---

.github/PULL_REQUEST_TEMPLATE.md

-----
1. Add a check for the `--dry-run` option in the PR template

chore: add check for dry-run opt in PR template

---

src/config.rs
src/main.rs
src/steps/generic.rs

Visual studio code IDE automatically updates extensions only when it is opened. It forces then to reload its windows, which is a (small but existing) annoyance.
I use Topgrade regularly with great success but observed it does not yet handle these extensions. I consequently made this PR to add this update.
Vscode extensions cli update is not trivial because no universal upgrade command exists ( a [coresponding issue](https://github.com/microsoft/vscode/issues/56578) has been opened but not implemented). The steps I use are:
- get list of installed extensions with `code --list-extensions` (obtain a line-return separated list of installed extensions)
- construct the upgrade command and execute it
- `code --force --install-extension [ext0] --install-extension [ext1] ... --install-extension …

feat: support Vscode packages updates

---

src/sudo.rs

-----
1. Deprioritize the `please` sudo in `Sudo::detect()` as it is [not that popular](https://crates.io/crates/pleaser) when compared to other sudo commands
1. For guys that are using `please`, if you have other sudo commands installed, this is a breaking change,  you need to manually set the sudo command to `please`:
```
[misc]
sudo_command = "please"
```
Closes #539

refactor: deprioritize please-sudo

---

config.example.toml
src/config.rs
src/main.rs

This allows setting a list of `log_filters` in the `[misc]` section in the `config.toml`. These filters are prepended to any filters listed with `--log-filters`. Finally, `--verbose` can now be used with `--log-filters`, and it will append `debug` to the list of filters rather than replacing it entirely.

Allow setting `misc.log_filters` in `config.toml`

---

src/steps/generic.rs
src/steps/git.rs
src/steps/os/unix.rs

`nix upgrade-nix` can be used on any platform except NixOS where `nix` is available.
Also use `nix profile upgrade --verbose` because the non-verbose mode doesn't print anything on stdout.
Also add `--extra-experimental-features nix-command` to `nix` invocations so that they don't error.

Fix "Nix" step to use `nix upgrade-nix` in more situations

---

src/main.rs
src/steps/git.rs

Before:
```
error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
Git repositories failed:
0: error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
0:
Location:
src/steps/git.rs:39
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
After:
```
Git repositories failed:
0: Failed to pull /Users/wiggles/.dotfiles
1: error: cannot pull with rebase: You have unstaged changes.
error: Please commit or stash them.
```

Make error messages nicer

---

config.example.toml
src/config.rs
src/steps/os/unix.rs

Last week `nix-env --upgrade` started compiling chromium because [its build](https://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.ungoogled-chromium.x86_64-linux) had not succeeded. To avoid compiling packages myself, I would like to be able to add `--prebuilt-only` to the nix-env arguments.
I have little experience with Rust, but everything seems to work as intended.

Add option for nix-env arguments

---

src/steps/os/windows.rs

Closes #521
@SteveLauC
---
I'd appreciate any feedback about this PR.

feat(wsl): pass verbose to topgrade-in-wsl

---

.github/PULL_REQUEST_TEMPLATE.md

----
Add check for the `--yes` option in the PR template

chore: add the check for the --yes opt in PR template

---

src/steps/os/linux.rs

fix: --yes option for protonup

---

.github/workflows/check-and-lint.yaml
src/steps/os/archlinux.rs

chore: bump CI toolchain to 1.73.0

---

src/steps/os/dragonfly.rs

* Include a missing use for a referenced type
* Add a missing step to do as is done on the FreeBSD code, which should be the same on this step as for DragonFly BSD
* Go against what clippy says for the sake of not actually crashing if an audit of packages fails. Absent this change, status_checked() will actually cause the run to crash at that step rather than say that that specific step failed and continue, which is not the expected behavior.
- [ X] The PR title is descriptive.
- [X ] The code compiles (`cargo build`)
- [X ] The code passes rustfmt (`cargo fmt`)
- [ X] The code passes tests (`cargo test`)
- [ X] *Optional:* I have tested the code myself
means to test it, please tag this …

Fix builds and runs on DragonFly BSD

---

src/steps/generic.rs

This PR add support for the yes option for the opam package manager.

fix: Support yes option for opam upgrade

---

.github/workflows/check-and-lint.yaml

In the past, I was manually bumping our CI toolchain when a new release was available, this is stupid, so let's make the GitHub action `rust-toolchain` do this for us.

chore: always use the latest stable toolchain for CI

---

src/steps/generic.rs

fix: disable dotnet greeting msg with DOTNET_NOLOGO=true

---

config.example.toml
src/config.rs
src/main.rs
src/steps/git.rs
src/steps/os/windows.rs
src/steps/zsh.rs

Fixes #562 
Not the most elegant solution I'll admit. I'm a little sad about the duplication but I was having some real issues with the async code and opaque types when I tried to deduplicate it. This implementation works at least (at least it did for my system, don't have a setup for more robust testing) so hopefully this is good enough for a first pass. I've added config options that seemed reasonable to me. Happy reviewing!

Add support for pushing custom git repositories

---

src/config.rs

In #574, we forgot to shell expand the paths, this PR fixes it.
```
$ cat ~/.config/topgrade/topgrade.toml
[misc]
assume_yes = true
disable = ["pip3", "gnome_shell_extensions", "node", "rustup", "containers", "firmware"]
pre_sudo = true
[git]
pull_predefined = false
pull_only_repos = [
"~/Documents/dotfiles",
]
$ topgrade --only git_repos -v --dry-run
DEBUG Step "Git repositories"
Path ~/Documents/dotfiles did not contain any git repositories
$ ./target/topgrade --only git_repos -v --dry-run
── 18:19:46 - Git repositories ─────────────────────────────────────────────────
Would pull /home/steve/Documents/dotfiles
```

fix: shellexpand git.pull_only_repos & git.push_only_repos

---

src/steps/git.rs

When I implemented this feature I maintained the push pull order for testing and forgot to switch it. Noticing now that this will make the step fail of only pulls are necessary. Switching the order should be good enough for the majority of cases, as it's what git itself suggests.

switch git push and pull order

---

src/command.rs
src/config.rs
src/ctrlc/windows.rs
src/main.rs
src/utils.rs

1. Make the logger work while loading the configuration file
A few days ago, I noticed that the configuration file was no longer printed in verbose mode, and found that our logger will ONLY be initialized after loading the config file, this behavior was introduced in #552, and this PR fixes it by setting our logger in 2 phases:
1. Set up it with the log level (filter directives) specified in the CLI option
```rs
let reload_handle = install_tracing(&opt.tracing_filter_directives())?;
```
2. Update it with the log levels specified in the CLI option and the config file
```rs
update_tracing(&reload_handle, &config.tracing_filter_directives())?; …
```

fix: make logger work while loading config file

---

config.example.toml
src/config.rs
src/steps/git.rs
src/steps/zsh.rs

1. Remove the following 3 macros:
1. check_deprecated
2. get_deprecated_moved_opt
3. get_deprecated_moved_or_default_to
They were added in previous versions and are not needed for now
> Though I do think `check_deprecated` is useful, but I tend to document breaking changes in the release note now
that `str_value!` macro is pretty good, we should probably switch all the impl functions of `Config` to it
2. Remove legacy fields from `struct Misc`
3. Rename `Repositories::remove()` to `remove_from_pull()`, and ONLY remove the repo from `self.pull_repos`
4. Add 1  helper function to `Repositories::pull_is_empty()`, which is needed by the …

refactor: remove legacy deprecated macros

---

src/config.rs
src/main.rs
src/self_update.rs

Make self_update a step
```sh
$ cargo b --features self-update -q
$ ./target/debug/topgrade  --only self_update
── 12:14:01 - Self update ──────────────────────────────────────────────────────
Checking target-arch... x86_64-unknown-linux-gnu
Checking current version... v10.0.2
Checking latest released version... v12.0.2
New release found! v10.0.2 --> v12.0.2
New release is *NOT* compatible
topgrade release status:
* Current exe: "/tmp/topgrade/target/debug/topgrade"
* New exe release: "topgrade-v12.0.2-x86_64-unknown-linux-gnu.tar.gz"
* New exe download url: "https://api.github.com/repos/topgrade-rs/topgrade/releases/assets/118492348"
The …
```

refactor: make SelfUpdate a step

---

src/steps/zsh.rs

fix: omz remote execution if ZSH is not present

---

config.example.toml

I'm only checking the first 2 as I believe the rest are not applicable here.

docs: fix typo in config.example.toml

---

README.md

1. Remind our users to check out the release note when updating to a major release
2. Remove the WIP doc as no one is seriously working on it right now, and the contents there is outdated

docs: migration and breaking changes

---

README.md
src/steps/zsh.rs

- [Y] The PR title is descriptive.
- [Y] I have read `CONTRIBUTING.md`
- [Y] The code compiles (`cargo build`)
- [Y] The code passes tests (`cargo test`)
- [Y] *Optional:* I have tested the code myself

Make zinit and zi use parallel updates

---

config.example.toml
src/config.rs
src/steps/containers.rs

Add a new option to skip containers to pull. This is my first time writing rust, so feedback is appreciated.
Tools like rancher-desktop add containers that cannot be pulled, resulting in errors.
This option allows to skip containers like these.

Add option to ignore containers to pull

---

src/steps/os/unix.rs

-----
According to issue #628, the brew option `--ignore-pinned` has been deprecated and is the default bahavior now, so let's remove it.

fix: remove deprecated brew option '--ignore-pinned'

---

src/main.rs
src/steps/os/unix.rs

`nix upgrade-nix` errors if `nix` is installed in a `nix profile`:
```
error: directory '/Users/wiggles/.nix-profile/bin' does not appear to be part of a Nix profile
```
Upstream issue: https://github.com/NixOS/nix/issues/5473
This patch duplicates the relevant Nix logic and skips running `nix upgrade-nix` if this error would occur: https://github.com/NixOS/nix/blob/f0180487a0e4c0091b46cb1469c44144f5400240/src/nix/upgrade-nix.cc#L102-L139
I've also split the `nix upgrade-nix` call into a separate step so we can use the `SkipStep` error messages appropriately.

Skip `nix upgrade-nix` when Nix is installed in a `nix profile`

---

src/steps/generic.rs

Closes #631 
From the information provided in #631, even though a pip3 is externally managed, we should still update it if `global.break-system-packages` is set to true.

refactor: update pip if extern managed and global.break-system-packages is true

---

src/steps/generic.rs

This commit introduces conditional logic to the `run_pipx_update` function that checks the installed version of pipx. If the version is 1.4.0 or higher, the `--quiet` argument is added to the `pipx upgrade-all` command to suppress non-critical output during the upgrade process, adhering to the new feature introduced in pipx 1.4.0 as per the documentation (https://pipx.pypa.io/stable/docs/#pipx-upgrade-all). This change aims to make the upgrade process less verbose and more manageable in automated scripts or CI/CD pipelines where log brevity is beneficial.

feat(pipx-update): add quiet flag for pipx upgrade-all on version 1.4.0+

---

src/steps/zsh.rs

This PR fixes #646 by using the script provided by @romkatv, I am not entirely sure about the root cause of that issue, but obviously, [the new script is better](https://github.com/topgrade-rs/topgrade/issues/646#issuecomment-1902569885), so let's use it instead, thanks for your help:)

fix: oh-my-zsh step issue #646

---

.github/workflows/update_homebrew.yml

---
> Warning: Homebrew/actions/bump-formulae is deprecated. Please use Homebrew/actions/bump-packages instead.
seeing in https://github.com/topgrade-rs/topgrade/actions/runs/7606040286/job/20711207212

workflows(homebrew): replace `Homebrew/actions/bump-formulae` with `Homebrew/actions/bump-packages`

---

.github/workflows/test-config-creation.yml
src/breaking_changes.rs
src/main.rs

-----
This PR adds a new feature that makes our breaking changes notification skippable, to do this, set `TOPGRADE_SKIP_BRKC_NOTIFY=true` when executing Topgrade:
```sh
$ TOPGRADE_SKIP_BRKC_NOTIFY=true topgrade
```

feat: skip breaking changes notification with env var

---

config.example.toml

Because OCD. Also added a description to max_concurrency to make this not as pointless.

Follow up to the follow up in #616

---

src/main.rs
src/steps/generic.rs
src/steps/os/linux.rs

Fixes #589
Fixes #593
Fixes #594
Fixes #609
This PR fixes the vscode extensions update in quite a few tricky situations by using the now upstreamed `code --update-extensions` command in the text editor ( [vscode/pull#199893](https://github.com/microsoft/vscode/pull/199893) ). This mean the step was completely rewritten.
Note that the command will only be released with January 2024 release (which should be published by early February) so this means I have NOT been able to properly test the code. This is why I create this as a draft until I can properly test it on the release.
Note also that `is_wls` is now a global function defined and …

fix vscode extensions update step

---

Cargo.lock
Cargo.toml
config.example.toml
src/steps/containers.rs

feat: support wildcard in ignored_containers

---

src/steps/os/macos.rs

This is just a simple fix on the macOS softwareupdate step, as the boolean `should_ask` wasn't conditional to dry runs prior.

fix: softwareupdate under dry run

---

src/config.rs
src/main.rs
src/steps/generic.rs

The `certbot` command does not seem to support this feature, right @bw1faeh0?

feat: certbot renew

---

src/steps/os/linux.rs
src/steps/os/os_release/wolfi

This adds support for updating Wolfi via Topgrade

feat: Add support for Wolfi

---

.github/workflows/check-and-lint.yaml

ci: run cargo test in ci

---

src/steps/generic.rs

Corrects a grammatical issue and a typo in two of the step output messages.

fix: correct typos in output

---

.github/workflows/check-and-lint.yaml

-----
1. Run CI checks on `aarch64-apple-darwin`
2. Bump macOS amd64 image to macOS-13

ci: add macOS aarch64 check

---

src/config.rs
src/main.rs
src/steps/os/linux.rs

Support a new step Waydroid, closes #684.

feat: support waydroid

---

.vscode/settings.json
config.example.toml
src/config.rs
src/steps/os/unix.rs

Adds a new boolean option `greedy_latest` in the config file for Brew/Homebrew, equivalent to the command line option `--greedy-latest` to `brew upgrade`, based on `greedy_cask` itself.
This is because `greedy_cask` invokes brew's `--greddy`, that updates "casks with auto_updates or version :latest". As I've been having some issues in apps with auto update, I decided to add this new option to allow for the git casks to be updated without touching the auto update ones.
Here is the result of the first test run:
<details>
<summary>Code test result</summary>
```code
topgrade/target/debug on  main [!] 
🍎 ❯ ./topgrade --only brew_cask brew_formula
── 21:19:04 - Topgrade 13.0.0 Breaking Changes ─────────────────────────────────
No Breaking changes
Confirmed? (y)es/(N)o
── 21:19:12 - Brew …
```

feat(brew): adds "greedy-latest" option to Brew

---

src/steps/zsh.rs

From zinit's [README](https://github.com/zdharma-continuum/zinit#automatic), it seems that they have changed their default install location from `~/.zinit` to `~/.local/share/zinit`, making our detection fail, this PR fixes it.

fix: zinit default install location

---

src/steps/generic.rs

Prior to this commit, helix grammars were fetched with sudo privileges. There is no need for this, and it was also a bug. Closes #697 .

Helix fetches grammar as a regular user

---

src/steps/generic.rs

The binary name of Helix varies from systems, on my host (Fedora, installed with `dnf`), it is called `hx` rather than helix, this PR enables Topgrade to search it with the binary name `hx`.

feat: also detect Helix step with bin name hx

---

src/steps/zsh.rs

Revert PR #614 as the `-p` option does not work properly.
Closes #709

revert: revert 614 to remove the -p option

---

src/config.rs
src/main.rs
src/steps/os/unix.rs

- Closes #626.
Runs `pyenv update` as the new `pyenv` step, given that all conditions are met:
+ OS is Unix (Windows not supported by Pyenv);
+ The `$PYENV_ROOT` env variable points to a valid location; and
+ `$PYENV_ROOT` points to a Git directory.
+ This last check might not be the case for other methods of installing `pyenv`, for which a `pyenv update` may not be available, or may fail.
- I ran `cargo run -- --verbose --only pyenv`, which works as expected for me, but I'm not sure where/how to add automated unit tests.
- underlying command does not support `--yes`.

Adds `pyenv` step

---

src/steps/generic.rs

This pull request adds `--include-injected` argument when running `pipx upgrade-all`, otherwise packages injected into the main apps' environments will not be updated.

fix(pipx): adds `--include-injected` argument to `pipx`

---

src/steps/os/unix.rs

fix: use env BUN_INSTALL to locate package.json

---

src/execution_context.rs
src/main.rs
src/steps/git.rs
src/steps/os/windows.rs
src/steps/zsh.rs

-----
This PR makes `GitRepos` an individual step, and it will collect git repos every time when the step is involved, so it should fixs #728.
cc @float3

refactor: make GitSteps a dedicated step

---

src/config.rs
src/main.rs
src/steps/generic.rs

It's like rustup/juliaup/ghcup/...

Add support for Lean 4's elan

---

src/runner.rs
src/utils.rs

1. Put step logs in a span so that we can clearly see which step a log entry belongs to.
Before:
```
DEBUG Cannot find "rpm-ostree"
DEBUG Detected "/usr/bin/dnf" as "dnf"
Dry running: /usr/bin/sudo /usr/bin/dnf upgrade -y
````
After:
```
DEBUG step{step=System key=System update}: Cannot find "rpm-ostree"
DEBUG step{step=System key=System update}: Detected "/usr/bin/dnf" as "dnf"
Dry running: /usr/bin/sudo /usr/bin/dnf upgrade -y
```

feat: put step logs in a span

---

src/config.rs
src/main.rs
src/steps/generic.rs

It should work
Does not seem to be supported
Closes #743

feat: support update ClamAV databases

---

src/config.rs
src/steps/vim.rs

Fixes 2 clippy lints :
1. unused_io_amount
2. unless_vec

style: fix 2 clippy lint unless_vec & unused_io_amount

---

src/steps/generic.rs

-----
On Windows, involving a command using `Command::new("binary_name")` can fail with error `Command not found` even though the corresponding binary is installed and put somewhere under `$PATH`, for example, #720.
There is a Rust issue for it: https://github.com/rust-lang/rust/issues/37519
A workaround is to use the `which` crate, which works in a way closer to how PowerShell handles cmd resolution, Topgrade's helper function `require()` uses `which()` under the hood, so this PR replaces those `Command::new("binary-name-string")` with `Command::new(a_path_returned_from_which)`.
Closes #720

fix: don't use Command::new(bin_name) as it won't work on Windows

---

src/steps/os/openbsd.rs

- [+] The PR title is descriptive.
- [+] I have read `CONTRIBUTING.md`
- [+] The code compiles (`cargo build`)
- [+] The code passes rustfmt (`cargo fmt`)
- [+] The code passes clippy (`cargo clippy`)
- [+] The code passes tests (`cargo test`)
fixes #708

FIXES #708: add config directive for pkg_* cleanup on OpenBSD

---

src/config.rs
src/main.rs
src/steps/os/unix.rs

Add support for mise-en-place (or mise). Mise is a tool like asdf (already supported). https://mise.jdx.dev/

feat: add support for mise

---

src/config.rs
src/main.rs
src/steps/generic.rs

Should work
Should work as there is only 1 command to execute
This does not seem to be supported
Closes #754

feat: support update PlatformIO Core

---

src/config.rs
src/main.rs

Strip the user when comparing the remote with the hostname of the local machine to prevent repeatedly running topgrade over SSH on localhost.
topgrade is run on a machine with a hostname equal to `host`, which has `user@host` present in the `remote_upgrades` list in `topgrade.toml`.
topgrade will trigger remote execution for `user@host` over SSH connection to `host`. This will repeat indefinitely due to the host recursively connecting to itself during each remote execution.
`user@host` remote will be recognized as being local to `host` and skipped by topgrade.

Fix local host detection for remotes with user 

---

src/steps/generic.rs

I've just run into the same error as #572, in the same scenario (right after updating .NET). I'm also fairly sure I've had it happen before.
If I remove the `.dotnet` folder in my home directory, I get this output from `dotnet tool list`:
```
> mv .dotnet .dotnet2
> DOTNET_NOLOGO=true dotnet tool list --global 2> /dev/null
An issue was encountered verifying workloads. For more information, run "dotnet workload update".
Package Id      Version      Commands
-------------------------------------
<list of packages>
```
I think this is the the cause of the error, although I'm not 100% sure. Either way, topgrade should parse out the header in a more reliable way than just skipping the first two lines of output. 
Well, it no longer fails after removing the `~/.dotnet` folder. Hopefully this …

fix: better `dotnet tool list` header parsing

---

BREAKINGCHANGES_dev.md
config.example.toml
src/config.rs
src/steps/git.rs

If `true`: the default, no change.
If `false`: Only show repositories that have been updated or have an error.
Minor tweak to output (removed colon) so that copy and paste for 'cd' is nicer.

Add config flag to toggle verbose Git repository output.

---

src/config.rs

refactor: 2 clippy warnings

---

src/config.rs
src/main.rs
src/steps/generic.rs

Rye is a new cargo-like package manager for python by @mitsuhiko.

Add rye support

---

src/config.rs
src/main.rs
src/steps/os/linux.rs

It should work considering this step involves only 1 command.
Does not seem to be supported: https://github.com/AdnanHodzic/auto-cpufreq?tab=readme-ov-file#update---auto-cpufreq-update
Closes #793

feat: support auto-cpufreq

---

.github/workflows/devskim.yml
.github/workflows/release-cross.yml
.github/workflows/release.yml

- [f] The code passes clippy (`cargo clippy`)

Dependatbot Updates

---

src/steps/os/linux.rs

run the debian upgrade steps if there is a linuxmint bedrock stratum.

add upgrade stuff for bedrock linuxmint strata

---

.github/workflows/create_release_assets.yml
.github/workflows/create_release_assets_cross.yml

`actions-rs/toolchain` and `action-rs/cargo` are deprecated, replace them with actions that are still maintained.
Ref: https://github.com/topgrade-rs/topgrade/issues/664#issuecomment-2026541629
No, since these 2 jobs will only be triggered in in a release.

ci: replace deprecated gh actions with alternatives

---

.github/workflows/check_security_vulnerability.yml
.github/workflows/ci.yml
.github/workflows/create_release_assets.yml

1. Build macOS binary for both arm64 and amd64, closes #678.
By the time of filing this PR, `macos-latest` is arm-only, and for public non-large runners, `macos-13` is the ONLY macOS runner that is still amd64.
3. Bump Linux runner to `ubunut-latest`.

chore: build binary for both macOS aarch64 and amd64

---

src/steps/os/linux.rs

Detect linuxmint distros and treat them as debian. 
Question: how does ubuntu work here? 
Mint is a Ubuntu fork and i have seen linuxmint strata getting the Ubuntu treatment in the upgrade_bedrock section, but i have not found any code that handles Ubuntu distros. But topgrade surely has support for the most popular distro of all, doesn't it? is it okay to treat ubuntu distros as debian?

Add linux mint support

---

src/steps/generic.rs

Currently, when updating RubyGems, the code defaults to sudo-ing it, unless there is `asdf` in the path. I've added checks for `rbenv` and `rvm` Ruby version managers to avoid using sudo.
The idea behind that piece of code may be faulty in the first place, and we should probably check the location or the file permissions of installed RubyGems instead of the pathname, but for a quick fix, should do.

fix(RubyGems): support no-sudo updating for rbenv and rvm

---

src/executor.rs
src/self_renamer.rs

Clear the following clippy warning:
```
error: field `0` is never read
--> src/executor.rs:230:9
|
[230](https://github.com/topgrade-rs/topgrade/actions/runs/9573017990/job/26393598748?pr=827#step:7:231) |     Wet(Child),
|     --- ^^^^^
|     |
|     field in this variant
|
= note: `-D dead-code` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(dead_code)]`
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
|
230 |     Wet(()),
|         ~~
```
It is indeed unused, but we should not remove it.

style: allow unused ExecutorChild

---

src/steps/tmux.rs

Before this PR, when updating tmux plugins, we only look for the update binary in its default location. The actual location can be altered via environment variable `TMUX_PLUGIN_MANAGER_PATH` so it should be considered as well.
fixes #832

fix: consider TMUX_PLUGIN_MANAGER_PATH when searching tpm binary

---

config.example.toml
src/config.rs
src/main.rs
src/steps/generic.rs

This PR adds support for updating [Lensfun](https://github.com/lensfun/lensfun)'s lenses database via its cli tool `lensfun-update-data`. 
Per the [documentation](https://lensfun.github.io/manual/v0.3.2/lensfun-update-data.html), this update command can be invoked with or without `sudo` so that one can decide where to install the update. If `sudo` is used, then the update will be installed system-wide, available to all users. Otherwise, update will be install under user's home directory and thus exclusive to the user.
This option is controlled through the following configuration entry in Topgrade:
```toml
[lensfun]
```
It should work as this is a one command step.
The `lensfun-update-data` command does not accept options.
If you developed a feature or a bug fix for …

feat: new step Lensfun's database update

---

src/config.rs

Noticed that the `--help` output and generated manpage use uppercased `Topgrade`, which is inconsistent and potentially confusing to users. This PR fixes that, and additionally restyles clap keywords.

Small clap adjustments

---

src/steps/os/unix.rs

Additional check before `pyenv update` is called. Fixes #849 when `pyenv` is managed by Homebrew or installed by cloning the repo without the required update plugin.
Try it by running
`cargo run -- --verbose --only pyenv`

Fix `pyenv: no such command 'update'` 

---

src/steps/os/unix.rs

Based on the discussion in #861, on Linux with systemd, `reboot` can be invoked without `sudo`, this PR implements it.
Closes #861.

feat: don't run reboot with sudo on Linux with systemd

---

src/steps/os/linux.rs
src/steps/os/os_release/nilrt

Add support for the `opkg` package manager used by the NI Linux Real-Time distribution.

feat(os): support NI Linux Real-Time's opkg package manager

---

src/config.rs
src/steps/os/linux.rs
src/steps/zsh.rs

Fixes some issues proposed by clippy, as requested in #871
Fixes #871

Fix nightly clippy warnings

---

.github/workflows/release_to_aur.yml

This PR change the action used to update AUR because the original one is not available on Github anymore.
I haven't been able to test myself as it's linked to topgrade CI.

ci: fix release_to_aur.yml

---

src/steps/os/unix.rs

Allow unfree packages to be upgraded
Fixes #611.

Allow Nix unfree packages to be upgraded

---

src/config.rs
src/main.rs
src/steps/node.rs

Currently there's no volta upgrade command, so this implementation has to list all installed packages first, and update them separately
Example output: 

feat: add volta packages

---

.github/workflows/release_to_winget.yml

Update the winget-releaser action in the release_to_winget.yml workflow to use the main branch instead of v2. This ensures that the latest version of the action is being used for publishing.

chore: update winget-releaser to use main branch

---

src/config.rs
src/main.rs
src/steps/generic.rs
src/steps/os/unix.rs

It adds the Aqua cli installer. 
https://aquaproj.github.io/

Add aqua tool installer cli

---

src/config.rs
src/main.rs
src/steps/generic.rs
src/steps/os/unix.rs

This `uv` step runs global update tasks for the relatively new [`uv`](https://github.com/astral-sh/uv) python package and project manager.
On update, two actions are executed:
1. `uv self update` [docs](https://docs.astral.sh/uv/getting-started/installation/#standalone-installer)
2. `uv tool upgrade --all` [docs](https://docs.astral.sh/uv/guides/tools/#installing-tools)
- `cargo run -- --verbose --only uv` works.
- underlying command does not support `--yes`.

Adds `uv` step

---

src/main.rs
src/steps/generic.rs
src/steps/os/unix.rs

From the [installaction page](https://bun.sh/docs/installation#windows), `bun` is available on Windows, so move it to `generic.rs`.

feat: support step Bun on Windows

---

src/config.rs

Fixes the panic described in #898.

fix: a panic introduced by improper unwrap()

---

.github/workflows/ci.yml
.github/workflows/create_release_assets.yml
.github/workflows/create_release_assets_cross.yml
Cargo.toml
README.md
rust-toolchain.toml

1. Pin the toolchain to 1.76.0
2. For our CI, remove the `dtolnay/rust-toolchain` action as it is no longer needed:   
1. GH CI provides `rustup` by default
2. We have the toolchain specified in `rust-toolchain.toml`
3. Thus, `cargo xxx` will download the toolchain automatically

chore: pin toolchain to MSRV(1.76)

---

src/steps/os/archlinux.rs

[Aura since version 4.0.6 no longer needs sudo](https://github.com/fosskers/aura/releases/tag/v4.0.6), so let's fix it on Topgrade's side.
Closes #907

fix: aura since v4.0.6 does not need sudo

---

src/steps/os/windows.rs

As described in issue #891, for the Scoop step, we should clean the cache if cleanup is enabled.

feat: clean scoop cache if cleanup is enabled

---

src/steps/generic.rs

Removes redundant auto_activate_base check. 
`mamba update --all -n base` should work whether the base is activated or not.
Fixes #731

Remove check for whether conda config contains auto_activate_base

---

src/steps/os/unix.rs

NOTE: This is my first contact with Rust, and the implementation is surely suboptimal.
Currently, on Linux, if the Homebrew installation directory is owned by a different user, the step fails.
Homebrew directory, which on Linux is `/home/linuxbrew/.linuxbrew/`, is typically owned by the user who installed Homebrew, or a dedicated user account.
This change ensures that Homebrew updates can proceed smoothly even when its directory ownership does not match the current user's UID. It accomplishes this by running the update command with `sudo`, changing the UID to the proper owner account. Appropriate sudo configuration is assumed for this to work properly, for example:
```
%wheel  ALL=(linuxbrew) CWD=/tmp NOPASSWD: /home/linuxbrew/.linuxbrew/Homebrew/bin/brew
```
If this feature is …

feat(brew): use sudo if Homebrew owned by another user on Linux

---

src/config.rs
src/main.rs
src/steps/generic.rs

Add Pixi upgrade to topgrade.
For reference:
https://github.com/prefix-dev/pixi/?tab=readme-ov-file#pixi-package-management-made-easy

Add Pixi to topgrade

---

CONTRIBUTING.md

We should never directly invoke `ctx.run_type().execute("binary_name_str")` as this can lead to issues on Windows due to 
the weird behavior of binary lookup in Rust std, always let `require()` do the binary lookup job. For example, here is an issue that we have encountered: https://github.com/topgrade-rs/topgrade/issues/725

docs: don't call execute("bin_name_str")

---

config.example.toml
src/config.rs
src/steps/os/unix.rs

Adds the ability to call Homebrew's `--greedy-auto-updates`, which upgrades casks with `auto_updates true` without including casks with `version :latest`.
This is useful to avoid upgrading packages marked with `:latest`, like fonts.
https://github.com/topgrade-rs/topgrade/pull/636

feat(brew): Add `greedy-auto-updates` option to Brew

---

src/config.rs

I think `--only` is not experimental now, so update the doc.

docs: --only is no longer experimental

---

locales/app.yml

This PR fixes some errors found by our checker:
```sh
$ ./topgrade_i18n_locale_file_checker --locale-file ../topgrade/locales/app.yml --rust-src-to-check ../topgrade/src
Errors Found:
UseOfKeysDoNotExist
file '../topgrade/src/self_update.rs' / line '52' / column '27' / key 'Respawning...'
file '../topgrade/src/steps/os/windows.rs' / line '202' / column '21' / key 'Could not find Topgrade in any WSL disribution'
file '../topgrade/src/steps/os/windows.rs' / line '209' / column '20' / key 'Windows Update'
file '../topgrade/src/main.rs' / line '488' / column '19' / key '\n(R)eboot\n(S)hell\n(Q)uit'
```
For the first 3 errors, they are keys that have not been added to our locale file. The last one is interesting, we already have it in the locale file:
```yaml
"\n(R)eboot\n(S)hell\n(Q)uit":
en: …
```

fix: use single quotes for locale keys with new line char

---

.github/workflows/check_i18n.yml

The locale file checker has been renamed, the binary name in CI should be updated as well.

ci: correct checker binary name

---

src/steps/os/unix.rs

Reverts PR #866 because it won't work [under specific cases](https://github.com/topgrade-rs/topgrade/issues/861#issuecomment-2295557398). We can still implement #861, but let's postpone it to the next release.

revert: PR 866

---

locales/app.yml
src/error.rs

Fix a typo in `exit_status`.
Maybe fixes issue #930
Output of failing step before patch:
```console
── 21:46:00 - Brew ─────────────────────────────────────────────────────────────
Brew failed: 
0: Command failed: `brew update`
1: `brew` failed: %{exit_satus}
Location:
src/steps/os/unix.rs:335
Retry? (y)es/(N)o/(s)hell/(q)uit
```
After patch:
```console
── 21:44:47 - Brew ─────────────────────────────────────────────────────────────
Brew failed: 
0: Command failed: `brew update`
1: `brew` failed: exit status: 1
Location:
src/steps/os/unix.rs:335
Retry? (y)es/(N)o/(s)hell/(q)uit
```

Fix typo in exit_status

---

locales/app.yml
src/steps/os/unix.rs

translated topgrade to zh_TW
#2 
Notes: the tests were successful but the locales doesn't show somehow

i18n(app.yml): new language zh_TW

---

.github/workflows/release_to_pypi.yml

Since there are breaking changes between the upload-artifact and download-artifact versions v3 and v4, this workflow was broken, and no releases were uploaded to pypi. A downgrade should make this work again.

fix: pypi-release-action: downgrade upload-artifact and download-artifact to v3

---

src/config.rs
src/steps/remote/vagrant.rs

Refactor config.rs and vagrant.rs files

---

locales/app.yml

Add Spanish localization (es).

i18n (app.yml): Add Spanish localization (es)

---

src/steps/os/unix.rs

Lix is a fork of Nix 2.18 focused on maintainability and user experience. It has a different format for the version, to distinguish it from CppNix:
$ nix --version
nix (Lix, like Nix) 2.91.0
This PR adjusts the Nix version parsing code to account for that, and also removes a few `panic!()`s along the way.
See: <https://lix.systems/>

Add support for Lix (Nix fork)

---

src/steps/os/openbsd.rs

This commit improves the -CURRENT detection by way of parsing `/etc/motd`. This change is more future-proof as when OpenBSD nears a stable release, `uname` will temporarily report like -STABLE.
This commit *also* adds feedback if -CURRENT is found to make debugging this feature easier with `--dry-run`, or, just a regular run as well.

Improve OpenBSD -CURRENT detection and Dry-run feedback

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

1. Document that newly-added user facing texts need to be translated.
2. Add a check list item for it.

docs: document that we need to translate user-facing texts

---

locales/app.yml
src/steps/os/openbsd.rs

In #923 and #954, we added some new messages that need i18n support, this PR does it.
Translations are provided by ChatGPT.

refactor: add missing i18n for OpenBSD steps

---

src/steps/os/unix.rs

Attempts to address issue previously encountered: https://github.com/topgrade-rs/topgrade/pull/757#issuecomment-2438658887
@returntrip

refactor: flip order of mise upgrade and mise plugins update

---

src/steps/generic.rs

uv step: checking self subcommand exits; fixes #942

---

locales/app.yml

i18n(app.yml): new language fr

---

config.example.toml
src/config.rs
src/steps/node.rs

Add config field for specifying deno version.

feat: allow version specification for deno

---

config.example.toml
src/config.rs
src/steps/generic.rs

This PR adds the `--startup-file=no` argument to the `julia` invocation for updating Julia packages. See [the upstream doc](https://docs.julialang.org/en/v1/manual/command-line-interface/#command-line-interface).
This is useful because if Julia has been recently updated (eg. with the `juliaup` step), then old versions of packages configured with `using` directives in `~/.julia/config/startup.jl` may fail to precompile or load with the new version, in turn causing the package update step to fail unnecessarily. By skipping the startup file load, broken or outdated packages will not attempt to be loaded.
- ~~[ ] If this PR introduces new user-facing messages they are translated~~

refactor: disable julia startup file for julia package update

---

config.example.toml
src/config.rs
src/steps/generic.rs

This skips the `poetry self update` step if poetry is not installed using the [official installer script](https://python-poetry.org/docs/#installing-with-the-official-installer), preventing externally-managed-environment errors if it was installed through e.g. a package manager.
I've also added a config option (`python.poetry_force_self_update`) that bypasses the check to always run `poetry self update` - this is useful for [manual installations](https://python-poetry.org/docs/#installing-manually). 
Fixes #979

fix(poetry): skip if not installed with official script

---

src/steps/os/linux.rs

This PR should fix https://github.com/topgrade-rs/topgrade/issues/997 where it wouldn't take the rpm-ostree flow when bootc was found on the system, even if it was disabled via the config.
Tested with `rpm-ostree=false` & `bootc=false` it used `dnf`
Tested with `rpm-ostree=true` & `bootc=false` it used `rpm-ostree`
Tested with `rpm-ostree=false` & `bootc=true` it used `bootc`
This was introducued in PR https://github.com/topgrade-rs/topgrade/pull/986
@tulilirockz maybe you can verify this also works for you.

fix: dont ignore rpm-ostree when bootc is found

---

src/steps/generic.rs

For the `uv` step, if the self-update feature is available, we should do the update and **check** its result.
cc @lucaspar 

refactor(uv step): check self update result if self-update feat is available

---

src/executor.rs

`CommandExt::output_checked()` returns `Err()` if the command fails, using it in `Executor::output()` will make its behavior different from `std::process::Command::output()`.
The same applies to `spawn()` as well. `Executor` does not have a `status()` command.
These changes were made 2 years ago by @9999years, it would be great if we can have you here and take a look at this PR:)

fix: Executor::spawn()/output() should not use their _checked() variants

---

src/steps/generic.rs

This PR runs `juliaup gc` to collect old julia versions if the `misc.cleanup` flag is set to true.

Run `juliaup gc` if cleanup is enabled

---

config.example.toml
src/config.rs
src/main.rs
src/steps/generic.rs

This PR adds a step to run [`zigup`](https://github.com/marler8997/zigup), a zig version manager comparable to the already-supported ZVM. The step can be configured to update multiple version tracking strings, mark them for keeping/clean up old versions, and change the directory they're installed into as well as the symlink path that they're "installed with".
By default, the step updates the `master` branch, which is currently considered the recommended version of zig (see "Tagged release or nightly build?" [here](https://ziglang.org/learn/getting-started/)), falling back to the default behaviour of `zigup` with paths, and not deleting any files.
the underlying command~~ **N/A**

Add zigup step

---

src/steps/generic.rs

Parse the shebang line in the poetry wrapper script to ignore leading spaces, and split out any arguments, so that e.g. `#! /usr/bin/python3 -sP` doesn't error. On Windows, take into account the possibility that the interpreter path may be double-quoted so that it can contain spaces.
Fixes #1021

fix(poetry): parse arg in script shebang line

---

src/config.rs
src/main.rs
src/steps/generic.rs
src/steps/os/linux.rs

Closes #1054
Adds a "Cinnamon spices" step that uses "cinnamon-spice-updater"
The step is currently guarded only for Linux and not for Linux Mint specifically. But I don't see why it would matter, since the command is only available on Linux Mint anyway. What do you think?

Add "Cinnamon spices" step

---

src/config.rs
src/main.rs
src/steps/generic.rs

Add pipxu step

---

src/steps/generic.rs

Conda provides a `conda clean` subcommand, sort of like `apt autoremove`, that automatically removes used unused packages, tarballs, and so on:
https://docs.conda.io/projects/conda/en/latest/commands/clean.html
This PR updates the Conda topgrade step to run `conda clean --all` if `cleanup = true` is set in the topgrade config. It adds `--yes` if topgrade is run with `-y`.
The same change is applied to the Mamba upgrade step, too (note that mamba and conda are nearly identical CLIs for working with conda environments).

Run `conda clean` after `conda update` if `cleanup = true`

---

src/steps/generic.rs

This adds `pixi global update`, which updates the global binaries installed through `pixi`, to the `pixi` step. The implementation follows #890 where the same was added for `uv`.

feat(pixi): add support for `pixi global`

---

src/sudo.rs

When the `sudo` binary is detected, an additional check is added to see whether it's actually `GSudo` masquerading as the `sudo` binary and the right `SudoKind` will be applied.
GSudo does this by making a `sudo.exe` that's symlinked to the `gsudo.exe` binary. We check if the canonical path of `sudo.exe` is equal to the canonical path of `gsudo.exe`, and apply `SudoKind::Gsudo` when true.
Additionally, during testing I've found that `gsudo status` doesn't cache credentials (it only shows whether credentials are currently cached and doesn't elevate), so `pre_sudo` likely never worked with `gsudo` in the first place. I've changed this to run `gsudo echo` instead, which does elevate and caches the credentials (if the credential cache has been enabled beforehand, of course).
Fixes issue …

fix(sudo): fix sudo detection & pre-sudo for GSudo

---

src/sudo.rs

Add `run0` (shipped by systemd since version 256) as a `sudo` variant.
the underlying command~~
~~If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.~~

feat(sudo): add run0 as a sudo variant

---

src/config.rs

Fixes the link in the `--log-filter`  description of when adding the `--help` option.
Issue: #1051 

docs: fix `--log-filter` link in `--help`

---

src/steps/emacs.el

Fix issue #1075. We'll use Emacs' embedded package upgrade functionality if available.
I don't know if we can use the i18n system to translate the string inside `emacs.el`.
Tested with Emacs 29.3 on Linux and Emacs 30.1 on macOS.

fix:(emacs): fix issue #1075

---

config.example.toml
src/config.rs
src/steps/os/windows.rs

This PR implements issue #1088 
Before I describe what this PR does, let me define "silent" in the Windows context. On Windows, historically, silent or quite when discussing installations means the installer does not present a GUI to the user and installs the software without interaction. **It does not mean suppressing command line output**. 
This PR makes Winget perform its upgrade silently, unless configured to not, by using the new `winget_install_silent` configuration option and setting it to `false` in the config file. Without this option set to `false`, Windows installers will launch an unattended installer window for the user. With this option set to `true` or left default, it will use the `--silent` command line argument tell Winget to attempt to run all application installers …

added silent install option for winget

---

src/steps/generic.rs

closes #1024
Check which of the two it is using `aqua --help`, checking for the string `aqua`.
JetBrains Aqua `aqua --help` output:
```
Some of the common commands and options (sorry, the full list is not yet supported):
--help      prints a short list of commands and options
--version   shows version information
/project/dir
opens a project from the given directory
[/project/dir|--temp-project] [--wait] [--line <line>] [--column <column>] file
opens the file, either in a context of the given project or as a temporary single-file project,
optionally waiting until the editor tab is closed
diff <left> <right>
opens a diff window between <left> and <right> files/directories
merge <local> <remote> [base] <merged>
opens a merge window between <local> and <remote> files (with optional common …
```

Fix aqua CLI and JetBrains Aqua conflict

---

.github/workflows/create_release_assets.yml

Closes #1095
Downgrade `create_release_assets.yml` workflow Ubuntu version to `22.04` from `24.04` / `ubuntu-latest`
This downgrades the `glibc` version it is built against, making it work on Debian 12 and Ubuntu 22.04 again. A new Rust version broke this.
I unfortunately cannot easily test if this actually work, but I would assume so. Could we release a new version ASAP for the affected people?
@SteveLauC are you familiar with this `glibc` version stuff? Do you agree this is the best course of action, or is there something else we should do?

Downgrade `create_release_assets.yml` workflow

---

src/steps/generic.rs

Allows the version format `"uv 0.6.14\n"` as well as `"uv 0.5.11 (c4d0caaee 2024-12-19)\n"`.
Closes #1120.
The problem #1105 solved should be unaffected.

Fix `uv` step

---

locales/app.yml
src/steps/os/linux.rs

Omits `deb-get clean` output, as it is very noisy and not useful.
Closes #1116

Omit `deb-get clean` output

---

src/steps/os/unix.rs

As of the latest version of asdf, the version has the format 0.16.7 - i.e. without the hash part.  This commit makes it so that both formats work.
Fixes #1096

Handle format change in asdf version

---

src/config.rs
src/main.rs
src/steps/generic.rs

Add Yazi step

---

src/steps/generic.rs

Like #1092, fix the conflict by inspecting the output of `hx --help`.
Closes #848

Fix conflict between hx (hexdump alternative) and Helix

---

src/steps/os/unix.rs

Closes #1137
- If the `nix --version` output contains exactly one dot (`.`), append `.0` to it.
- Use `output_changed_message!` here as well
```console
[gideon@gideon-pc-lin ~/projects/topgrade] (main *=) 1 (14.9s)
$ sh <(curl -L https://nixos.org/nix/install) --no-daemon
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4267  100  4267    0     0  19253      0 --:--:-- --:--:-- --:--:-- 19253
downloading Nix 2.28.2 binary tarball for x86_64-linux from 'https://releases.nixos.org/nix/nix-2.28.2/nix-2.28.2-x86_64-linux.tar.xz' to '/tmp/nix-binary-tarball-unpack.xRC9TNmBRL'...
% Total    % Received % Xferd  Average Speed   Time    Time …
```

Fix nix version output changed

---

Cargo.lock
Cargo.toml
src/steps/generic.rs
src/steps/os/unix.rs
src/terminal.rs

Drop `lazy_static` for std's `LazyLock`.

Drop lazy_static

---

.github/workflows/release_to_pypi.yml

Update the "release to PyPI" CI file to fix the [error](https://github.com/topgrade-rs/topgrade/actions/runs/15633044633/job/44041594597#step:1:27):
```sh
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-[1](https://github.com/topgrade-rs/topgrade/actions/runs/15633044633/job/44041594597#step:1:1)6-deprecation-notice-v3-of-the-artifact-actions/
```
Also, configure the `workflow_dispatch` event so that we can run this pipeline manually.

ci: fix pipeline relase to PyPI

---

.github/workflows/create_release_assets.yml

[I forgot to replace all the uses of `github.event.release.tag_name` with the tag name that comes from our custom step ("Determine tag name")](https://github.com/topgrade-rs/topgrade/issues/1170#issuecomment-2975395674), which causes the invalid filename. This PR fixes it.
Also, for our custom step, specify the shell to bash so that it works on Windows as well.

ci: use the new tag name and specify shell to bash

---

locales/app.yml
src/steps/generic.rs
src/utils.rs

Add support for tools to have multiple possible binaries because IntellIj IDEA on the AUR can have multiple depending on the edition.
[AUR Ultimate Edition](https://aur.archlinux.org/packages/intellij-idea-ultimate-edition) and [AUR Community Edition](https://aur.archlinux.org/packages/intellij-idea-community-edition-bin) renames the binary to `intellij-idea-ultimate-edition` and `intellij-idea-community-edition` respectively.
_Google translated_

Add support for multiple binary names and idea having multiple binaries

---

Cargo.lock
Cargo.toml
src/config.rs

(alphabetically)
Closes #1181
Technically this is a breaking change.
```console
$ cargo run -- --only custom_commands
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.60s
Running `target/debug/topgrade --only custom_commands`
── 13:55:04 - B command ────────────────────────────────────────────────────────
This should be first
── 13:55:04 - A command ────────────────────────────────────────────────────────
This should be second
── 13:55:04 - Summary ──────────────────────────────────────────────────────────
B command: OK
A command: OK
```

Preserve custom commmand order from config instead of sorting

---

locales/app.yml

"ya" isn't a word. :-) 
Fixes the "y/n/s/q" string in the German translation: made the accessor keys casing even, applied the same style, fixed the word "ya".

fixed the German translation for "y/n/s/q"

---

.github/workflows/create_release_assets.yml

Closes https://github.com/topgrade-rs/topgrade/issues/1207
Seems to work, results from my fork for a fake tag: https://github.com/scop/topgrade/attestations
Note that the freebsd attestation is missing but that's expected, because the freebsd build failed due to unrelated reasons.

Generate artifact attestations for release assets

---

Cargo.lock
Cargo.toml
src/main.rs

Replaces the `once_cell` crate with equivalent functionality provided by `std (1.80)` via [`LazyLock`](https://doc.rust-lang.org/beta/std/sync/struct.LazyLock.html).

refactor: replace once_cell crate with std equivalent

---

src/sudo.rs

Replace an `_` with a `-` in `sudo`'s `--preserve-env=...` argument.
https://www.man7.org/linux/man-pages/man8/sudo.8.html

Sudo preserve env list argument is `--preserve-env`

---

Cargo.lock
Cargo.toml
src/utils.rs

Updates `tracing-subscriber` to ~0.3.20 to address GHSA-xwfj-jgwm-7wp5, preventing ANSI escape sequence injection in logs. Also enables required `winapi` features on Windows to fix build issues (no behavior change).
- Update `tracing-subscriber = ~0.3.20` (features: `env-filter`, `time`)
- Windows: enable `winapi` features (`consoleapi`, `wincon`) to resolve missing imports
- Windows: cargo build successful
- Debian WSL: `cargo build --locked` successful; `topgrade --version` and `--help` run
- No user-facing changes, no config/i18n changes
- Logging behavior unchanged
- https://github.com/advisories/GHSA-xwfj-jgwm-7wp5
Mitigates ANSI escape injection in logs by pinning `tracing-subscriber` to the fixed version and documents the rationale.

Security: update tracing-subscriber to ~0.3.20 (ANSI escape injection fix, GHSA-xwfj-jgwm-7wp5)

---

src/main.rs
src/step.rs
src/steps/os/unix.rs

Fixes a few simple spelling issues in code and comments. No functional changes.
Changes
- `src/main.rs`: rename local variable for clarity — `splitted` → `parts`; use `parts.next()` for var/value extraction.
- `src/steps/os/unix.rs`: comment typo — `wether` → `whether`.
- `src/step.rs`: user-visible label typo — “GitHub CLI Extenstions” → “GitHub CLI Extensions”.
Intentionally not included
- No configuration, documentation, templates, or workflow changes.
- No formatting/tooling policy changes.
- `cargo build` — PASS
- `cargo fmt` — N/A (no formatting changes)
- `cargo clippy` — N/A (no behavioral changes)
- `cargo test` — N/A (no tests affected)
- This PR is …

chore: fix simple typos in code and comments (split var, whether, Extensions)

---

src/steps/os/windows.rs

Closes #1097
Changes how topgrade is executed in the `WSL` step by making the shell a login shell.
When topgrade (in windows) searches for `topgrade` in wsl, it uses a login shell (`bash -lc ...`). When actually executing, it doesn't (`bash -c ...`). Because of that certain shell setup files are not loaded and topgrade (in wsl) cannot find / execute all steps.

use login shell when executing topgrade

---

src/steps/generic.rs
src/steps/os/windows.rs
src/steps/powershell.rs

Some simple refactoring, moving the step logic out of `Powershell` and into the respective calling functions under `steps/*`. I think it's cleaner this way, `Powershell` is then just a wrapper for running PowerShell commands, rather than having step logic that just uses PowerShell to run commands but don't have much to do with PowerShell itself.

Move step logic out of Powershell struct

---

Cargo.lock
Cargo.toml
config.example.toml
locales/app.yml
src/config.rs
src/main.rs
src/steps/generic.rs
src/steps/os/unix.rs
src/steps/os/windows.rs
src/steps/powershell.rs
src/sudo.rs
src/utils.rs

Adds a warning message if running as root, followed by a yes/no confirmation prompt.
Also adds a "null" sudo, which just runs the command directly. If Topgrade is running as root/elevated, this is used instead of calling `Sudo::detect()`.
On Windows, it doesn't print the warning, as running commands as Administrator usually doesn't cause the same kind of problems as on Unix systems. I've used the single-function `is_elevated` crate to do the elevated check here.
- I haven't excluded the "null" sudo from being set in the config file, so you could use `sudo_command = "null"` to get the null sudo even when not running as administrator. Not sure why you'd ever want to do that, but maybe it could be useful somewhere.
- Also if a `sudo_command` is set in the config file, that is always used …

Detect when running as root/elevated, and skip using sudo in this case

---

src/steps/containers.rs

Suppresses the `--platform` parameter to docker pull if platform is only '/'.
This is my first Rust code contribution. I hope it's ok. 
I couldn't find unit tests for the containers.rs file. If there are any, please point me to them.
fixes #1154

fix(containers):  Docker update fails on M Macs due to platform /
